LOCATION_MAPPING = {
	[8] = "@JohtoKanto/Violet City/Gym - TM31 from Falkner", --NPCGift
	[9] = "@JohtoKanto/Azalea Town/Gym - TM49 from Bugsy", --NPCGift
	[10] = "@JohtoKanto/Cianwood City/Gym - TM01 from Chuck", --NPCGift
	[11] = "@JohtoKanto/Goldenrod City/Gym - TM45 from Whitney", --NPCGift
	[12] = "@JohtoKanto/Ecruteak City/Gym - TM30 from Morty", --NPCGift
	[13] = "@JohtoKanto/Olivine City/Gym - TM23 from Jasmine", --NPCGift
	[14] = "@JohtoKanto/Mahogany Town/Gym - TM16 from Pryce", --NPCGift
	[15] = "@JohtoKanto/Blackthorn Gym/TM24 from Clair", --NPCGift
	[16] = "@JohtoKanto/Ilex Forest/HM01 from Farfetch'd Guy", --HM
	[17] = "@JohtoKanto/Cianwood City/HM02 from Chuck's Wife", --HM
	[18] = "@JohtoKanto/Ecruteak City/Dance Theater - HM03 from Theater Director", --HM
	[19] = "@JohtoKanto/Olivine City/HM04 from Sailor in Cafe", --HM
	[20] = "@JohtoKanto/Sprout Tower/3F - HM05 from Sage", --HM
	[21] = "@JohtoKanto/Mahogany Town/Rocket HQ B2F - HM06 from Lance", --HM
	[23] = "@JohtoKanto/Route 32/Old Rod from Pokecenter Fishing Guru", --NPCGift
	[24] = "@JohtoKanto/Olivine City/Good Rod from Fishing Guru", --NPCGift
	[25] = "@JohtoKanto/Route 12/Super Rod from Fishing Guru", --NPCGift
	[35] = "@JohtoKanto/Cianwood City/Pharmacy - Secretpotion", --NPCGift
	[36] = "@JohtoKanto/New Bark Town/Elm's Lab - S.S. Ticket from Elm", --NPCGift
	[39] = "@JohtoKanto/Route 30/Berry from House", --NPCGift
	[53] = "@JohtoKanto/Azalea Town/Lure Ball from Kurt", --NPCGift
	[62] = "@JohtoKanto/Route 39/Moomoo Farm - TM13 After Feeding Moomoo", --NPCGift
	[71] = "@JohtoKanto/Radio Tower/3F - TM11 from Woman", --NPCGift
	[72] = "@JohtoKanto/Radio Tower/4F - Pink Bow from Mary", --NPCGift
	[74] = "@JohtoKanto/Goldenrod Underground/Warehouse - Card Key from Director", --NPCGift
	[75] = "@JohtoKanto/Route 36/TM08 from Rock Smash Guy", --NPCGift
	[77] = "@JohtoKanto/Cherrygrove City/Mystic Water from Island Man", --NPCGift
	[78] = "@JohtoKanto/Route 32/TM05 from Roar Guy", --NPCGift
	[82] = "@JohtoKanto/Route 35/HP Up After Delivering Kenya", --NPCGift
	[83] = "@JohtoKanto/Route 31/TM50 for Delivering Kenya", --NPCGift
	[87] = "@JohtoKanto/National Park/Quick Claw from Lady", --NPCGift
	[88] = "@JohtoKanto/Lake of Rage/TM10 from Hidden Power House", --NPCGift
	[89] = "@JohtoKanto/Route 43/Sludge Bomb from Guard in Gate", --NPCGift
	[90] = "@JohtoKanto/Ecruteak City/Itemfinder from Itemfinder Guy", --NPCGift
	[91] = "@JohtoKanto/Goldenrod City/Bicycle from Bike Shop", --NPCGift
	[92] = "@JohtoKanto/Goldenrod City/Squirtbottle from Flower Shop", --NPCGift
	[93] = "@JohtoKanto/Route 32/Miracle Seed from Man in North", --NPCGift
	[94] = "@JohtoKanto/Azalea Town/Charcoal from Charcoal Kiln", --NPCGift
	[95] = "@JohtoKanto/Ilex Forest/TM02 from Headbutt Guy", --NPCGift
	[99] = "@JohtoKanto/Route 32/Poison Barb from Frieda", --NPCGift
	[101] = "@JohtoKanto/Route 29/Pink Bow from Tuscany", --NPCGift
	[103] = "@JohtoKanto/Route 36/Hard Stone from Arthur", --NPCGift
	[105] = "@JohtoKanto/Route 37/Magnet from Sunny", --NPCGift
	[107] = "@JohtoKanto/Lake of Rage/Blackbelt from Wesley", --NPCGift
	[109] = "@JohtoKanto/Blackthorn City/Spell Tag from Santos", --NPCGift
	[111] = "@JohtoKanto/Route 40/Sharp Beak from Monica", --NPCGift
	[112] = "@JohtoKanto/Route 34/Soft Sand from Kate", --NPCGift
	[113] = "@JohtoKanto/S.S. Aqua/Metal Coat from Grandpa", --NPCGift
	[114] = "@JohtoKanto/Dark Cave Blackthorn Entrance/Blackglasses from Man", --NPCGift
	[115] = "@JohtoKanto/Slowpoke Well/B2F - Kings Rock from Man", --NPCGift
	[116] = "@JohtoKanto/Route 28/Steel Wing from Celebrity in House", --NPCGift
	[117] = "@JohtoKanto/Route 27/Sandstorm from Woman in House", --NPCGift
	[120] = "@JohtoKanto/Radio Tower/5F - Clear Bell from Rocket Boss", --NPCGift
	[121] = "@JohtoKanto/Pewter City/Silver Wing from Old Man", --NPCGift
	[122] = "@JohtoKanto/Route 34/TM12 from Woman in Gate", --NPCGift
	[124] = "@JohtoKanto/New Bark Town/Elm's Lab - Master Ball from Elm", --NPCGift
	[125] = "@JohtoKanto/Tin Tower/4F - Hidden Item in Center", --Hidden
	[126] = "@JohtoKanto/Tin Tower/5F - Hidden Item in Southeast", --Hidden
	[127] = "@JohtoKanto/Tin Tower/5F - Hidden Item in Southwest", --Hidden
	[128] = "@JohtoKanto/Burned Tower/1F - Hidden Item 1", --Hidden
	[132] = "@JohtoKanto/National Park/Hidden Item Behind Fence", --Hidden
	[133] = "@JohtoKanto/Olivine Lighthouse/5F - Hidden Item", --Hidden
	[134] = "@JohtoKanto/Mahogany Town/Rocket HQ B1F - Hidden Item in West", --Hidden
	[135] = "@JohtoKanto/Mahogany Town/Rocket HQ B2F - Hidden Item", --Hidden
	[136] = "@JohtoKanto/Ilex Forest/Hidden Item 1", --Hidden
	[137] = "@JohtoKanto/Ilex Forest/Hidden Item 3", --Hidden
	[138] = "@JohtoKanto/Ilex Forest/Hidden Item 2", --Hidden
	[139] = "@JohtoKanto/Goldenrod Underground/Hidden Item Between Tables", --Hidden
	[140] = "@JohtoKanto/Goldenrod Underground/Hidden Item in Center", --Hidden
	[141] = "@JohtoKanto/Goldenrod Underground/Hidden Item by Blue Door", --Hidden
	[142] = "@JohtoKanto/Goldenrod Underground/B2F - Hidden Item 1", --Hidden
	[143] = "@JohtoKanto/Goldenrod Underground/B2F - Hidden Item 2", --Hidden
	[144] = "@JohtoKanto/Mount Mortar/1F Outside - Hidden Item", --Hidden
	[145] = "@JohtoKanto/Mount Mortar/1F Inside - Hidden Item", --Hidden
	[146] = "@JohtoKanto/Mount Mortar/2F - Hidden Item", --Hidden
	[147] = "@JohtoKanto/Mount Mortar/B1F - Hidden Item on Boulder", --Hidden
	[148] = "@JohtoKanto/Ice Path/B1F - Hidden Item on Boulder", --Hidden
	[149] = "@JohtoKanto/Ice Path/B2F - Hidden Item in Corner", --Hidden
	[150] = "@JohtoKanto/Ice Path/B2F - Hidden Item on Boulder", --Hidden
	[151] = "@JohtoKanto/Whirl Islands/B1F - Hidden Item in Northeast", --Hidden
	[152] = "@JohtoKanto/Whirl Islands/B1F - Hidden Item in East", --Hidden
	[153] = "@JohtoKanto/Whirl Islands/B1F - Hidden Item on Boulder in West", --Hidden
	[154] = "@JohtoKanto/Silver Cave/1F - Hidden Item 1", --Hidden
	[155] = "@JohtoKanto/Silver Cave/1F - Hidden Item 2", --Hidden
	[156] = "@JohtoKanto/Silver Cave/2F - Hidden Item", --Hidden
	[157] = "@JohtoKanto/Dark Cave Violet Entrance/Hidden Item in North", --Hidden
	[158] = "@JohtoKanto/Victory Road/2F - Hidden Item on Northwest Boulder", --Hidden
	[159] = "@JohtoKanto/Victory Road/1F - Hidden Item on Southwest Boulder", --Hidden
	[160] = "@JohtoKanto/Blackthorn City/Dragon's Den B1F - Hidden Item in SE Corner", --Hidden
	[161] = "@JohtoKanto/Blackthorn City/Dragon's Den B1F - Hidden Item in Water 2", --Hidden
	[162] = "@JohtoKanto/Blackthorn City/Dragon's Den B1F - Hidden Item in Water 1", --Hidden
	[163] = "@JohtoKanto/Route 28/Hidden Item Behind Cut Tree", --Hidden
	[164] = "@JohtoKanto/Route 30/Hidden Item in Flowers", --Hidden
	[165] = "@JohtoKanto/Route 32/Hidden Item by Frieda", --Hidden
	[166] = "@JohtoKanto/Route 32/Hidden Item North of Bridge", --Hidden
	[167] = "@JohtoKanto/Route 34/Hidden Item Across Water", --Hidden
	[168] = "@JohtoKanto/Route 34/Hidden Item in Day-Care Yard", --Hidden
	[169] = "@JohtoKanto/Route 37/Hidden Item", --Hidden
	[170] = "@JohtoKanto/Route 39/Hidden Item Between Miltank", --Hidden
	[171] = "@JohtoKanto/Route 40/Hidden Item in Rock", --Hidden
	[172] = "@JohtoKanto/Whirl Islands/Hidden Item on Southwest Island", --Hidden
	[173] = "@JohtoKanto/Route 42/Hidden Item in Pond Rock", --Hidden
	[174] = "@JohtoKanto/Route 44/Hidden Item Across Water", --Hidden
	[175] = "@JohtoKanto/Route 45/Hidden Item in Southeast Pond", --Hidden
	[176] = "@JohtoKanto/Violet City/Hidden Item Behind Cut Tree", --Hidden
	[177] = "@JohtoKanto/Azalea Town/Hidden Item By Well", --Hidden
	[178] = "@JohtoKanto/Cianwood City/Hidden Item in North Rock", --Hidden
	[179] = "@JohtoKanto/Cianwood City/Hidden Item in West Rock", --Hidden
	[180] = "@JohtoKanto/Ecruteak City/Hidden Item by Pond", --Hidden
	[181] = "@JohtoKanto/Lake of Rage/Hidden Item in West Path", --Hidden
	[182] = "@JohtoKanto/Lake of Rage/Hidden Item Behind Cut Tree", --Hidden
	[183] = "@JohtoKanto/Lake of Rage/Hidden Item in Northeast", --Hidden
	[184] = "@JohtoKanto/Silver Cave/Outside - Hidden Item Across Water", --Hidden
	[200] = "@JohtoKanto/Route 2/Nugget from Guy", --NPCGift
	[209] = "@JohtoKanto/Saffron City/Pass from Copycat", --NPCGift
	[210] = "@JohtoKanto/Vermilion City/Lost Item from Guy in Fan Club", --KeyItem
	[212] = "@JohtoKanto/Vermilion City/Rare Candy from Fan Club President", --NPCGift
	[216] = "@JohtoKanto/Route 25/Nugget Bridge Prize", --NPCGift
	[218] = "@JohtoKanto/Celadon City/TM03 from Man in Mansion Roof", --NPCGift
	[219] = "@JohtoKanto/Route 5/Cleanse Tag from Woman in House", --NPCGift
	[220] = "@JohtoKanto/Celadon City/Gym - TM19 from Erika", --NPCGift
	[221] = "@JohtoKanto/Fuchsia City/Gym - TM06 from Janine", --NPCGift
	[222] = "@JohtoKanto/Saffron City/Silph Co. 1F - Up-Grade from Guard", --NPCGift
	[223] = "@JohtoKanto/Power Plant/TM07 from Manager", --NPCGift
	[224] = "@JohtoKanto/Viridian City/TM42 from Sleepy Guy", --NPCGift
	[226] = "@JohtoKanto/Vermilion City/HP Up from Man by PokeCenter", --NPCGift
	[227] = "@JohtoKanto/Saffron City/TM29 from Mr Psychic", --NPCGift
	[228] = "@JohtoKanto/Diglett's Cave/Hidden Item on Boulder", --Hidden
	[229] = "@JohtoKanto/Route 5/Underground Path - Hidden Item in North", --Hidden
	[230] = "@JohtoKanto/Route 5/Underground Path - Hidden Item in South", --Hidden
	[231] = "@JohtoKanto/Rock Tunnel/1F - Hidden Item 1", --Hidden
	[232] = "@JohtoKanto/Rock Tunnel/1F - Hidden Item 2", --Hidden
	[233] = "@JohtoKanto/Rock Tunnel/B1F - Hidden Item", --Hidden
	[234] = "@JohtoKanto/Olivine City/Port - Hidden Item in Southeast Buoy", --Hidden
	[235] = "@JohtoKanto/Vermilion City/Port - Hidden Item in Buoy", --Hidden
	[237] = "@JohtoKanto/Route 2/Hidden Item 3", --Hidden
	[238] = "@JohtoKanto/Route 2/Hidden Item 1", --Hidden
	[239] = "@JohtoKanto/Route 2/Hidden Item 2", --Hidden
	[240] = "@JohtoKanto/Route 2/Hidden Item 4", --Hidden
	[241] = "@JohtoKanto/Route 4/Hidden Item on Plateau", --Hidden
	[242] = "@JohtoKanto/Route 9/Hidden Item in Southeast Corner", --Hidden
	[243] = "@JohtoKanto/Route 12/Hidden Item on Island", --Hidden
	[244] = "@JohtoKanto/Route 13/Hidden Item in Fence Maze", --Hidden
	[245] = "@JohtoKanto/Route 11/Hidden Item in Tree", --Hidden
	[246] = "@JohtoKanto/Route 17/Hidden Item at Corner", --Hidden
	[247] = "@JohtoKanto/Route 17/Hidden Item in Fence", --Hidden
	[248] = "@JohtoKanto/Route 25/Hidden Item in Tree", --Hidden
	[250] = "@JohtoKanto/Cerulean City/Hidden Item in Water", --Hidden
	[251] = "@JohtoKanto/Cerulean City/Gym - Machine Part in Water", --KeyIyem
	[252] = "@JohtoKanto/Vermilion City/Hidden Item by Gym", --Hidden
	[253] = "@JohtoKanto/Celadon City/Hidden Item At Dead End", --Hidden
	[254] = "@JohtoKanto/Cinnabar Island/Hidden Item in North", --Hidden
	[255] = "@JohtoKanto/Burned Tower/1F - Hidden Item 2", --Hidden
	[261] = "@JohtoKanto/Violet City/Gym - Zephyr Badge from Falkner", --Badge
	[262] = "@JohtoKanto/Azalea Town/Gym - Hive Badge from Bugsy", --Badge
	[263] = "@JohtoKanto/Goldenrod City/Gym - Plain Badge from Whitney", --Badge
	[264] = "@JohtoKanto/Ecruteak City/Gym - Fog Badge from Morty", --Badge
	[265] = "@JohtoKanto/Cianwood City/Gym - Storm Badge from Chuck", --Badge
	[266] = "@JohtoKanto/Olivine City/Gym - Mineral Badge from Jasmine", --Badge
	[267] = "@JohtoKanto/Mahogany Town/Gym - Glacier Badge from Pryce", --Badge
	[268] = "@JohtoKanto/Blackthorn Gym/Rising Badge from Clair", --Badge
	[269] = "@JohtoKanto/Pewter City/Gym - Boulder Badge from Brock", --Badge
	[270] = "@JohtoKanto/Cerulean City/Gym - Cascade Badge from Misty", --Badge
	[271] = "@JohtoKanto/Vermilion City/Gym - Thunder Badge from Lt. Surge", --Badge
	[272] = "@JohtoKanto/Celadon City/Gym - Rainbow Badge from Erika", --Badge
	[273] = "@JohtoKanto/Fuchsia City/Gym - Soul Badge from Janine", --Badge
	[274] = "@JohtoKanto/Saffron City/Gym - Marsh Badge from Sabrina", --Badge
	[275] = "@JohtoKanto/Seafoam Islands/Gym - Volcano Badge from Blaine", --Badge
	[276] = "@JohtoKanto/Viridian City/Gym - Earth Badge from Blue", --Badge
	[277] = "@JohtoKanto/New Bark Town/Elm's Lab - Potion from Aide", --NPCGift
	[278] = "@JohtoKanto/Route 30/Mystery Egg from Mr Pokemon", --NPCGift
	[279] = "@JohtoKanto/Route 30/Exp Share from Mr Pokemon", --NPCGift
	[280] = "@JohtoKanto/Lake of Rage/Red Scale from Gyarados", --KeyItem
	[281] = "@JohtoKanto/New Bark Town/Elm's Lab - Gift from Aide After Returning Mystery Egg", --NPCGift
	[282] = "@JohtoKanto/Radio Tower/1F - Radio Card from Quiz", --NPCGift,Pokegear
	[283] = "@JohtoKanto/Cherrygrove City/Map Card from Guide", --NPCGift,Pokegear
	[285] = "@JohtoKanto/Lavender Town/Radio Tower - EXPN Card", --NPCGift
	[286] = "@JohtoKanto/New Bark Town/Player's House - Pokegear from Mom", --NPCGift
	[551] = "@JohtoKanto/Radio Tower/2F - Blue Card from Buena", --NPCGift
	[950] = "@JohtoKanto/Radio Tower/5F - Basement Key from False Director", --NPCGift
	[1039] = "@JohtoKanto/Route 40/Swimmer Elaine", --Trainersanity
	[1040] = "@JohtoKanto/Route 40/Swimmer Paula", --Trainersanity
	[1041] = "@JohtoKanto/Route 41/Swimmer Kaylee", --Trainersanity
	[1042] = "@JohtoKanto/Route 41/Swimmer Susie", --Trainersanity
	[1043] = "@JohtoKanto/Route 41/Swimmer Denise", --Trainersanity
	[1044] = "@JohtoKanto/Route 41/Swimmer Kara", --Trainersanity
	[1045] = "@JohtoKanto/Route 41/Swimmer Wendy", --Trainersanity
	[1050] = "@JohtoKanto/Route 19/Swimmer Dawn", --Trainersanity
	[1052] = "@JohtoKanto/Route 20/Swimmer Nicole", --Trainersanity
	[1053] = "@JohtoKanto/Route 20/Swimmer Lori", --Trainersanity
	[1055] = "@JohtoKanto/Route 21/Swimmer Nikki", --Trainersanity
	[1056] = "@JohtoKanto/Cerulean City/Gym - Swimmer Diana", --Trainersanity
	[1057] = "@JohtoKanto/Cerulean City/Gym - Swimmer Briana", --Trainersanity
	[1058] = "@JohtoKanto/Violet City/Gym - Bird Keeper Rod", --Trainersanity
	[1059] = "@JohtoKanto/Violet City/Gym - Bird Keeper Abe", --Trainersanity
	[1060] = "@JohtoKanto/Route 35/Bird Keeper Bryan", --Trainersanity
	[1061] = "@JohtoKanto/Olivine Lighthouse/3F - Bird Keeper Theo", --Trainersanity
	[1062] = "@JohtoKanto/Route 38/Bird Keeper Toby", --Trainersanity
	[1063] = "@JohtoKanto/Olivine Lighthouse/5F - Bird Keeper Denis", --Trainersanity
	[1064] = "@JohtoKanto/Route 44/Bird Keeper Vance", --Trainersanity
	[1065] = "@JohtoKanto/Route 4/Bird Keeper Hank", --Trainersanity
	[1066] = "@JohtoKanto/Route 14/Bird Keeper Roy", --Trainersanity
	[1067] = "@JohtoKanto/Route 18/Bird Keeper Boris", --Trainersanity
	[1068] = "@JohtoKanto/Route 18/Bird Keeper Bob", --Trainersanity
	[1070] = "@JohtoKanto/Route 32/Bird Keeper Peter", --Trainersanity
	[1071] = "@JohtoKanto/Route 27/Bird Keeper Jose", --Trainersanity
	[1072] = "@JohtoKanto/Route 13/Bird Keeper Perry", --Trainersanity
	[1073] = "@JohtoKanto/Route 13/Bird Keeper Bret", --Trainersanity
	[1077] = "@JohtoKanto/Mahogany Town/Gym - Boarder Ronald", --Trainersanity
	[1078] = "@JohtoKanto/Mahogany Town/Gym - Boarder Brad", --Trainersanity
	[1079] = "@JohtoKanto/Mahogany Town/Gym - Boarder Douglas", --Trainersanity
	[1080] = "@JohtoKanto/Sprout Tower/1F - Sage Chow", --Trainersanity
	[1081] = "@JohtoKanto/Sprout Tower/2F - Sage Nico", --Trainersanity
	[1082] = "@JohtoKanto/Sprout Tower/3F - Sage Jin", --Trainersanity
	[1083] = "@JohtoKanto/Sprout Tower/3F - Sage Troy", --Trainersanity
	[1084] = "@JohtoKanto/Ecruteak City/Gym - Sage Jeffrey", --Trainersanity
	[1085] = "@JohtoKanto/Ecruteak City/Gym - Sage Ping", --Trainersanity
	[1086] = "@JohtoKanto/Sprout Tower/2F - Sage Edmond", --Trainersanity
	[1087] = "@JohtoKanto/Sprout Tower/3F - Sage Neal", --Trainersanity
	[1089] = "@JohtoKanto/Route 32/Camper Roland", --Trainersanity
	[1090] = "@JohtoKanto/Route 34/Camper Todd", --Trainersanity
	[1091] = "@JohtoKanto/Route 35/Camper Ivan", --Trainersanity
	[1092] = "@JohtoKanto/Route 35/Camper Elliot", --Trainersanity
	[1094] = "@JohtoKanto/Route 25/Camper Lloyd", --Trainersanity
	[1095] = "@JohtoKanto/Route 9/Camper Dean", --Trainersanity
	[1096] = "@JohtoKanto/Route 9/Camper Sid", --Trainersanity
	[1099] = "@JohtoKanto/Route 46/Camper Ted", --Trainersanity
	[1106] = "@JohtoKanto/Pewter City/Gym - Camper Jerry", --Trainersanity
	[1107] = "@JohtoKanto/Route 43/Camper Spencer", --Trainersanity
	[1108] = "@JohtoKanto/Goldenrod Underground/B2F - Burglar Duncan", --Trainersanity
	[1109] = "@JohtoKanto/Goldenrod Underground/B2F - Burglar Eddie", --Trainersanity
	[1110] = "@JohtoKanto/S.S. Aqua/1F - Burglar Corey (Westbound)", --Trainersanity
	[1114] = "@JohtoKanto/Route 8/Biker Dwayne", --Trainersanity
	[1115] = "@JohtoKanto/Route 8/Biker Harris", --Trainersanity
	[1116] = "@JohtoKanto/Route 8/Biker Zeke", --Trainersanity
	[1117] = "@JohtoKanto/Route 17/Biker Charles", --Trainersanity
	[1118] = "@JohtoKanto/Route 17/Biker Riley", --Trainersanity
	[1119] = "@JohtoKanto/Route 17/Biker Joel", --Trainersanity
	[1120] = "@JohtoKanto/Route 17/Biker Glenn", --Trainersanity
	[1121] = "@JohtoKanto/Ruins of Alph/Outside - Psychic Nathan", --Trainersanity
	[1122] = "@JohtoKanto/Saffron City/Gym - Psychic Franklin", --Trainersanity
	[1123] = "@JohtoKanto/Route 11/Psychic Herman", --Trainersanity
	[1124] = "@JohtoKanto/Route 11/Psychic Fidel", --Trainersanity
	[1125] = "@JohtoKanto/Route 37/Psychic Greg", --Trainersanity
	[1126] = "@JohtoKanto/Route 39/Psychic Norman", --Trainersanity
	[1127] = "@JohtoKanto/Route 36/Psychic Mark", --Trainersanity
	[1128] = "@JohtoKanto/Route 44/Psychic Phil", --Trainersanity
	[1129] = "@JohtoKanto/Route 26/Psychic Richard", --Trainersanity
	[1130] = "@JohtoKanto/Route 27/Psychic Gilbert", --Trainersanity
	[1131] = "@JohtoKanto/Saffron City/Gym - Psychic Jared", --Trainersanity
	[1132] = "@JohtoKanto/S.S. Aqua/1F - Psychic Rodney (Eastbound)", --Trainersanity
	[1133] = "@JohtoKanto/Route 3/Firebreather Otis", --Trainersanity
	[1136] = "@JohtoKanto/Route 3/Firebreather Burt", --Trainersanity
	[1137] = "@JohtoKanto/Union Cave/1F - Firebreather Bill", --Trainersanity
	[1138] = "@JohtoKanto/Route 35/Firebreather Walt", --Trainersanity
	[1139] = "@JohtoKanto/Union Cave/1F - Firebreather Ray", --Trainersanity
	[1141] = "@JohtoKanto/Route 32/Fisher Justin", --Trainersanity
	[1142] = "@JohtoKanto/Route 32/Fisher Ralph", --Trainersanity
	[1143] = "@JohtoKanto/Route 21/Fisher Arnold", --Trainersanity
	[1144] = "@JohtoKanto/Route 12/Fisher Kyle", --Trainersanity
	[1145] = "@JohtoKanto/Route 32/Fisher Henry", --Trainersanity
	[1146] = "@JohtoKanto/Route 43/Fisher Marvin", --Trainersanity
	[1147] = "@JohtoKanto/Route 42/Fisher Tully", --Trainersanity
	[1148] = "@JohtoKanto/Lake of Rage/Fisher Andre", --Trainersanity
	[1149] = "@JohtoKanto/Lake of Rage/Fisher Raymond", --Trainersanity
	[1150] = "@JohtoKanto/Route 44/Fisher Wilton", --Trainersanity
	[1151] = "@JohtoKanto/Route 44/Fisher Edgar", --Trainersanity
	[1152] = "@JohtoKanto/S.S. Aqua/B1F - Fisher Jonah (Eastbound)", --Trainersanity
	[1153] = "@JohtoKanto/Route 12/Fisher Martin", --Trainersanity
	[1154] = "@JohtoKanto/Route 12/Fisher Stephen", --Trainersanity
	[1155] = "@JohtoKanto/Route 12/Fisher Barney", --Trainersanity
	[1161] = "@JohtoKanto/Route 26/Fisher Scott", --Trainersanity
	[1163] = "@JohtoKanto/Azalea Town/Gym - Twins Amy & May", --Trainersanity
	[1164] = "@JohtoKanto/Route 37/Twins Ann & Anne", --Trainersanity
	[1167] = "@JohtoKanto/Celadon City/Gym - Twins Jo & Zoe", --Trainersanity
	[1171] = "@JohtoKanto/National Park/Schoolboy Jack", --Trainersanity
	[1172] = "@JohtoKanto/Route 15/Schoolboy Kipp", --Trainersanity
	[1173] = "@JohtoKanto/Route 36/Schoolboy Alan", --Trainersanity
	[1174] = "@JohtoKanto/Route 15/Schoolboy Johnny", --Trainersanity
	[1175] = "@JohtoKanto/Route 1/Schoolboy Danny", --Trainersanity
	[1176] = "@JohtoKanto/Route 15/Schoolboy Tommy", --Trainersanity
	[1177] = "@JohtoKanto/Route 25/Schoolboy Dudley", --Trainersanity
	[1178] = "@JohtoKanto/Route 25/Schoolboy Joe", --Trainersanity
	[1179] = "@JohtoKanto/Route 15/Schoolboy Billy", --Trainersanity
	[1180] = "@JohtoKanto/Route 38/Schoolboy Chad", --Trainersanity
	[1181] = "@JohtoKanto/S.S. Aqua/B1F - Schoolboy Nate (Westbound)", --Trainersanity
	[1182] = "@JohtoKanto/S.S. Aqua/B1F - Schoolboy Ricky (Westbound)", --Trainersanity
	[1189] = "@JohtoKanto/Route 32/Picnicker Liz", --Trainersanity
	[1190] = "@JohtoKanto/Route 34/Picnicker Gina", --Trainersanity
	[1191] = "@JohtoKanto/Route 35/Picnicker Brooke", --Trainersanity
	[1192] = "@JohtoKanto/Route 35/Picnicker Kim", --Trainersanity
	[1194] = "@JohtoKanto/Route 4/Picnicker Hope", --Trainersanity
	[1195] = "@JohtoKanto/Route 4/Picnicker Sharon", --Trainersanity
	[1198] = "@JohtoKanto/Route 46/Picnicker Erin", --Trainersanity
	[1201] = "@JohtoKanto/Route 9/Picnicker Heidi", --Trainersanity
	[1202] = "@JohtoKanto/Route 9/Picnicker Edna", --Trainersanity
	[1207] = "@JohtoKanto/Celadon City/Gym - Picnicker Tanya", --Trainersanity
	[1208] = "@JohtoKanto/Route 43/Picnicker Tiffany", --Trainersanity
	[1210] = "@JohtoKanto/S.S. Aqua/1F - Guitarist Clyde (Westbound)", --Trainersanity
	[1211] = "@JohtoKanto/Vermilion City/Gym - Guitarist Vincent", --Trainersanity
	[1212] = "@JohtoKanto/Route 35/Juggler Irwin", --Trainersanity
	[1214] = "@JohtoKanto/Vermilion City/Gym - Juggler Horton", --Trainersanity
	[1217] = "@JohtoKanto/Olivine Lighthouse/3F - Gentleman Preston", --Trainersanity
	[1218] = "@JohtoKanto/S.S. Aqua/1F - Gentleman Edward (Eastbound)", --Trainersanity
	[1219] = "@JohtoKanto/Vermilion City/Gym - Gentleman Gregory", --Trainersanity
	[1221] = "@JohtoKanto/Olivine Lighthouse/2F - Gentleman Alfred", --Trainersanity
	[1222] = "@JohtoKanto/Mahogany Town/Rocket HQ B3F - Scientist Ross", --Trainersanity
	[1223] = "@JohtoKanto/Mahogany Town/Rocket HQ B3F - Scientist Mitch", --Trainersanity
	[1224] = "@JohtoKanto/Mahogany Town/Rocket HQ B1F - Scientist Jed", --Trainersanity
	[1225] = "@JohtoKanto/Radio Tower/3F - Scientist Marc", --Trainersanity
	[1226] = "@JohtoKanto/Radio Tower/4F - Scientist Rich", --Trainersanity
	[1228] = "@JohtoKanto/Cianwood City/Gym - Blackbelt Yoshi", --Trainersanity
	[1230] = "@JohtoKanto/Cianwood City/Gym - Blackbelt Lao", --Trainersanity
	[1231] = "@JohtoKanto/Cianwood City/Gym - Blackbelt Nob", --Trainersanity
	[1233] = "@JohtoKanto/Cianwood City/Gym - Blackbelt Lung", --Trainersanity
	[1234] = "@JohtoKanto/Route 45/Blackbelt Kenji", --Trainersanity
	[1235] = "@JohtoKanto/S.S. Aqua/B1F - Blackbelt Wai (Eastbound)", --Trainersanity
	[1236] = "@JohtoKanto/Goldenrod City/Gym - Beauty Victoria", --Trainersanity
	[1237] = "@JohtoKanto/Goldenrod City/Gym - Beauty Samantha", --Trainersanity
	[1241] = "@JohtoKanto/S.S. Aqua/1F - Beauty Cassie (Eastbound)", --Trainersanity
	[1249] = "@JohtoKanto/Celadon City/Gym - Beauty Julia", --Trainersanity
	[1251] = "@JohtoKanto/Route 38/Beauty Valerie", --Trainersanity
	[1268] = "@JohtoKanto/National Park/Pokefan William", --Trainersanity
	[1269] = "@JohtoKanto/Route 39/Pokefan Derek", --Trainersanity
	[1270] = "@JohtoKanto/Route 10/Pokefan Robert", --Trainersanity
	[1271] = "@JohtoKanto/Route 13/Pokefan Joshua", --Trainersanity
	[1272] = "@JohtoKanto/Route 14/Pokefan Carter", --Trainersanity
	[1273] = "@JohtoKanto/Route 14/Pokefan Trevor", --Trainersanity
	[1274] = "@JohtoKanto/Route 34/Pokefan Brandon", --Trainersanity
	[1275] = "@JohtoKanto/S.S. Aqua/1F - Pokefan Jeremy (Westbound)", --Trainersanity
	[1279] = "@JohtoKanto/Route 13/Pokefan Alex", --Trainersanity
	[1280] = "@JohtoKanto/National Park/Pokefan Beverly", --Trainersanity
	[1281] = "@JohtoKanto/Route 39/Pokefan Ruth", --Trainersanity
	[1284] = "@JohtoKanto/S.S. Aqua/1F - Pokefan Georgia (Westbound)", --Trainersanity
	[1286] = "@JohtoKanto/Ecruteak City/Dance Theater - Kimono Girl Naoko", --Trainersanity
	[1287] = "@JohtoKanto/Ecruteak City/Dance Theater - Kimono Girl Sayo", --Trainersanity
	[1288] = "@JohtoKanto/Ecruteak City/Dance Theater - Kimono Girl Zuki", --Trainersanity
	[1289] = "@JohtoKanto/Ecruteak City/Dance Theater - Kimono Girl Kuni", --Trainersanity
	[1290] = "@JohtoKanto/Ecruteak City/Dance Theater - Kimono Girl Miki", --Trainersanity
	[1291] = "@JohtoKanto/Union Cave/1F - Pokemaniac Larry", --Trainersanity
	[1292] = "@JohtoKanto/Union Cave/B1F - Pokemaniac Andrew", --Trainersanity
	[1293] = "@JohtoKanto/Union Cave/B1F - Pokemaniac Calvin", --Trainersanity
	[1294] = "@JohtoKanto/Route 42/Pokemaniac Shane", --Trainersanity
	[1295] = "@JohtoKanto/Route 43/Pokemaniac Ben", --Trainersanity
	[1296] = "@JohtoKanto/Route 43/Pokemaniac Brent", --Trainersanity
	[1297] = "@JohtoKanto/Route 43/Pokemaniac Ron", --Trainersanity
	[1298] = "@JohtoKanto/S.S. Aqua/1F - Pokemaniac Ethan (Westbound)", --Trainersanity
	[1301] = "@JohtoKanto/Goldenrod Underground/Pokemaniac Issac", --Trainersanity
	[1302] = "@JohtoKanto/Goldenrod Underground/Pokemaniac Donald", --Trainersanity
	[1303] = "@JohtoKanto/Route 44/Pokemaniac Zach", --Trainersanity
	[1304] = "@JohtoKanto/Slowpoke Well/B1F - Grunt 2", --Trainersanity
	[1305] = "@JohtoKanto/Slowpoke Well/B1F - Grunt 3", --Trainersanity
	[1306] = "@JohtoKanto/Radio Tower/1F - Grunt", --Trainersanity
	[1307] = "@JohtoKanto/Radio Tower/2F - Grunt 1", --Trainersanity
	[1308] = "@JohtoKanto/Radio Tower/2F - Grunt 2", --Trainersanity
	[1309] = "@JohtoKanto/Radio Tower/2F - Grunt 3", --Trainersanity
	[1310] = "@JohtoKanto/Radio Tower/3F - Grunt 1", --Trainersanity
	[1311] = "@JohtoKanto/Radio Tower/3F - Grunt 2", --Trainersanity
	[1312] = "@JohtoKanto/Radio Tower/3F - Grunt 3", --Trainersanity
	[1313] = "@JohtoKanto/Radio Tower/4F - Grunt 1", --Trainersanity
	[1314] = "@JohtoKanto/Goldenrod Underground/B2F - Grunt 1", --Trainersanity
	[1316] = "@JohtoKanto/Goldenrod Underground/B2F - Grunt 3", --Trainersanity
	[1317] = "@JohtoKanto/Goldenrod Underground/Warehouse - Grunt 2", --Trainersanity
	[1318] = "@JohtoKanto/Goldenrod Underground/Warehouse - Grunt 3", --Trainersanity
	[1319] = "@JohtoKanto/Mahogany Town/Rocket HQ B1F - Grunt", --Trainersanity
	[1320] = "@JohtoKanto/Mahogany Town/Rocket HQ B2F - Grunt 1", --Trainersanity
	[1321] = "@JohtoKanto/Mahogany Town/Rocket HQ B2F - Grunt 2", --Trainersanity
	[1322] = "@JohtoKanto/Mahogany Town/Rocket HQ B2F - Grunt 3", --Trainersanity
	[1327] = "@JohtoKanto/Goldenrod Underground/Warehouse - Grunt 1", --Trainersanity
	[1328] = "@JohtoKanto/Goldenrod Underground/B2F - Grunt 2", --Trainersanity
	[1331] = "@JohtoKanto/Mahogany Town/Rocket HQ B3F - Grunt 2", --Trainersanity
	[1332] = "@JohtoKanto/Slowpoke Well/B1F - Grunt 1", --Trainersanity
	[1335] = "@JohtoKanto/Slowpoke Well/B1F - Grunt 4", --Trainersanity
	[1336] = "@JohtoKanto/Radio Tower/2F - Grunt 4", --Trainersanity
	[1337] = "@JohtoKanto/Goldenrod Underground/B2F - Grunt 4", --Trainersanity
	[1338] = "@JohtoKanto/Radio Tower/4F - Grunt 2", --Trainersanity
	[1339] = "@JohtoKanto/Mahogany Town/Rocket HQ B3F - Grunt 1", --Trainersanity
	[1340] = "@JohtoKanto/Goldenrod City/Gym - Lass Carrie", --Trainersanity
	[1341] = "@JohtoKanto/Goldenrod City/Gym - Lass Bridget", --Trainersanity
	[1343] = "@JohtoKanto/National Park/Lass Krise", --Trainersanity
	[1344] = "@JohtoKanto/Olivine Lighthouse/4F - Lass Connie", --Trainersanity
	[1346] = "@JohtoKanto/Route 25/Lass Laura", --Trainersanity
	[1347] = "@JohtoKanto/Route 25/Lass Shannon", --Trainersanity
	[1348] = "@JohtoKanto/Celadon City/Gym - Lass Michelle", --Trainersanity
	[1349] = "@JohtoKanto/Route 38/Lass Dana", --Trainersanity
	[1350] = "@JohtoKanto/Route 25/Lass Ellen", --Trainersanity
	[1356] = "@JohtoKanto/Union Cave/1F - Hiker Russell", --Trainersanity
	[1357] = "@JohtoKanto/Union Cave/B1F - Hiker Phillip", --Trainersanity
	[1358] = "@JohtoKanto/Union Cave/B1F - Hiker Leonard", --Trainersanity
	[1359] = "@JohtoKanto/Route 33/Hiker Anthony", --Trainersanity
	[1360] = "@JohtoKanto/Route 42/Hiker Benjamin", --Trainersanity
	[1361] = "@JohtoKanto/Route 45/Hiker Erik", --Trainersanity
	[1362] = "@JohtoKanto/Route 45/Hiker Michael", --Trainersanity
	[1363] = "@JohtoKanto/Route 45/Hiker Parry", --Trainersanity
	[1364] = "@JohtoKanto/Route 45/Hiker Timothy", --Trainersanity
	[1365] = "@JohtoKanto/Route 46/Hiker Bailey", --Trainersanity
	[1367] = "@JohtoKanto/Route 9/Hiker Tim", --Trainersanity
	[1369] = "@JohtoKanto/Route 9/Hiker Sidney", --Trainersanity
	[1370] = "@JohtoKanto/Route 13/Hiker Kenny", --Trainersanity
	[1371] = "@JohtoKanto/Route 10/Hiker Jim", --Trainersanity
	[1372] = "@JohtoKanto/Union Cave/1F - Hiker Daniel", --Trainersanity
	[1375] = "@JohtoKanto/Route 30/Bug Catcher Don", --Trainersanity
	[1376] = "@JohtoKanto/Route 2/Bug Catcher Rob", --Trainersanity
	[1377] = "@JohtoKanto/Route 2/Bug Catcher Ed", --Trainersanity
	[1378] = "@JohtoKanto/Route 31/Bug Catcher Wade", --Trainersanity
	[1379] = "@JohtoKanto/Azalea Town/Gym - Bug Catcher Benny", --Trainersanity
	[1380] = "@JohtoKanto/Azalea Town/Gym - Bug Catcher Al", --Trainersanity
	[1381] = "@JohtoKanto/Azalea Town/Gym - Bug Catcher Josh", --Trainersanity
	[1382] = "@JohtoKanto/Route 35/Bug Catcher Arnie", --Trainersanity
	[1383] = "@JohtoKanto/S.S. Aqua/1F - Bug Catcher Ken (Westbound)", --Trainersanity
	[1386] = "@JohtoKanto/Route 2/Bug Catcher Doug", --Trainersanity
	[1391] = "@JohtoKanto/Union Cave/B2F - Cool Trainer Nick", --Trainersanity
	[1392] = "@JohtoKanto/Lake of Rage/Cool Trainer Aaron", --Trainersanity
	[1393] = "@JohtoKanto/Blackthorn City/Gym - 1F - Cool Trainer Paul", --Trainersanity
	[1394] = "@JohtoKanto/Blackthorn City/Gym - 2F - Cool Trainer Cody", --Trainersanity
	[1395] = "@JohtoKanto/Blackthorn Gym/1F - Cool Trainer Mike", --Trainersanity
	[1398] = "@JohtoKanto/Route 45/Cool Trainer Ryan", --Trainersanity
	[1399] = "@JohtoKanto/Route 26/Cool Trainer Jake", --Trainersanity
	[1400] = "@JohtoKanto/Route 26/Cool Trainer Gaven", --Trainersanity
	[1401] = "@JohtoKanto/Route 27/Cool Trainer Blake", --Trainersanity
	[1402] = "@JohtoKanto/Route 27/Cool Trainer Brian", --Trainersanity
	[1406] = "@JohtoKanto/S.S. Aqua/1F - Cool Trainer Sean (Eastbound)", --Trainersanity
	[1409] = "@JohtoKanto/Route 44/Cool Trainer Allen", --Trainersanity
	[1410] = "@JohtoKanto/Union Cave/B2F - Cool Trainer Gwen", --Trainersanity
	[1411] = "@JohtoKanto/Lake of Rage/Cool Trainer Lois", --Trainersanity
	[1412] = "@JohtoKanto/Blackthorn City/Gym - 2F - Cool Trainer Fran", --Trainersanity
	[1413] = "@JohtoKanto/Blackthorn Gym/1F - Cool Trainer Lola", --Trainersanity
	[1414] = "@JohtoKanto/Route 34/Cool Trainer Kate", --Trainersanity
	[1415] = "@JohtoKanto/Route 34/Cool Trainer Irene", --Trainersanity
	[1416] = "@JohtoKanto/Route 45/Cool Trainer Kelly", --Trainersanity
	[1417] = "@JohtoKanto/Route 26/Cool Trainer Joyce", --Trainersanity
	[1418] = "@JohtoKanto/Route 26/Cool Trainer Beth", --Trainersanity
	[1419] = "@JohtoKanto/Route 27/Cool Trainer Reena", --Trainersanity
	[1420] = "@JohtoKanto/Route 27/Cool Trainer Megan", --Trainersanity
	[1422] = "@JohtoKanto/S.S. Aqua/1F - Cool Trainer Carol (Eastbound)", --Trainersanity
	[1423] = "@JohtoKanto/Route 1/Cool Trainer Quinn", --Trainersanity
	[1424] = "@JohtoKanto/Union Cave/B2F - Cool Trainer Emma", --Trainersanity
	[1425] = "@JohtoKanto/Route 44/Cool Trainer Cybil", --Trainersanity
	[1426] = "@JohtoKanto/Route 34/Cool Trainer Jenn", --Trainersanity
	[1430] = "@JohtoKanto/Radio Tower/5F - Rocket Executive", --Trainersanity
	[1433] = "@JohtoKanto/Radio Tower/4F - Rocket Executive", --Trainersanity
	[1436] = "@JohtoKanto/Route 39/Sailor Eugene", --Trainersanity
	[1437] = "@JohtoKanto/Olivine Lighthouse/2F - Sailor Huey", --Trainersanity
	[1438] = "@JohtoKanto/Olivine Lighthouse/3F - Sailor Terrell", --Trainersanity
	[1439] = "@JohtoKanto/Olivine Lighthouse/4F - Sailor Kent", --Trainersanity
	[1440] = "@JohtoKanto/Olivine Lighthouse/5F - Sailor Ernest", --Trainersanity
	[1442] = "@JohtoKanto/S.S. Aqua/B1F - Sailor Garrett (Eastbound)", --Trainersanity
	[1443] = "@JohtoKanto/S.S. Aqua/B1F - Sailor Kenneth (Westbound)", --Trainersanity
	[1445] = "@JohtoKanto/Route 38/Sailor Harry", --Trainersanity
	[1448] = "@JohtoKanto/Ruins of Alph/Outside - Super Nerd Stan", --Trainersanity
	[1449] = "@JohtoKanto/Goldenrod Underground/Super Nerd Eric", --Trainersanity
	[1453] = "@JohtoKanto/Route 8/Super Nerd Sam", --Trainersanity
	[1454] = "@JohtoKanto/Route 8/Super Nerd Tom", --Trainersanity
	[1455] = "@JohtoKanto/Route 25/Super Nerd Pat", --Trainersanity
	[1456] = "@JohtoKanto/S.S. Aqua/1F - Super Nerd Shawn (Eastbound)", --Trainersanity
	[1457] = "@JohtoKanto/Goldenrod Underground/Super Nerd Teru", --Trainersanity
	[1458] = "@JohtoKanto/Ecruteak City/Gym - Medium Martha", --Trainersanity
	[1459] = "@JohtoKanto/Ecruteak City/Gym - Medium Grace", --Trainersanity
	[1463] = "@JohtoKanto/Saffron City/Gym - Medium Rebecca", --Trainersanity
	[1464] = "@JohtoKanto/Saffron City/Gym - Medium Doris", --Trainersanity
	[1465] = "@JohtoKanto/Mahogany Town/Gym - Skier Roxanne", --Trainersanity
	[1466] = "@JohtoKanto/Mahogany Town/Gym - Skier Clarissa", --Trainersanity
	[1467] = "@JohtoKanto/Route 19/Swimmer Harold", --Trainersanity
	[1468] = "@JohtoKanto/Route 40/Swimmer Simon", --Trainersanity
	[1469] = "@JohtoKanto/Route 40/Swimmer Randall", --Trainersanity
	[1470] = "@JohtoKanto/Route 41/Swimmer Charlie", --Trainersanity
	[1471] = "@JohtoKanto/Route 41/Swimmer George", --Trainersanity
	[1472] = "@JohtoKanto/Route 41/Swimmer Berke", --Trainersanity
	[1473] = "@JohtoKanto/Route 41/Swimmer Kirk", --Trainersanity
	[1474] = "@JohtoKanto/Route 41/Swimmer Mathew", --Trainersanity
	[1480] = "@JohtoKanto/Route 19/Swimmer Jerome", --Trainersanity
	[1481] = "@JohtoKanto/Route 19/Swimmer Tucker", --Trainersanity
	[1483] = "@JohtoKanto/Route 20/Swimmer Cameron", --Trainersanity
	[1484] = "@JohtoKanto/Route 21/Swimmer Seth", --Trainersanity
	[1487] = "@JohtoKanto/Cerulean City/Gym - Swimmer Parker", --Trainersanity
	[1488] = "@JohtoKanto/Route 30/Youngster Joey", --Trainersanity
	[1489] = "@JohtoKanto/Route 30/Youngster Mikey", --Trainersanity
	[1490] = "@JohtoKanto/Route 32/Youngster Albert", --Trainersanity
	[1491] = "@JohtoKanto/Route 32/Youngster Gordon", --Trainersanity
	[1492] = "@JohtoKanto/Route 34/Youngster Samuel", --Trainersanity
	[1493] = "@JohtoKanto/Route 34/Youngster Ian", --Trainersanity
	[1496] = "@JohtoKanto/Route 3/Youngster Warren", --Trainersanity
	[1497] = "@JohtoKanto/Route 3/Youngster Jimmy", --Trainersanity
	[1498] = "@JohtoKanto/Route 11/Youngster Owen", --Trainersanity
	[1499] = "@JohtoKanto/Route 11/Youngster Jason", --Trainersanity
	[1500] = "@JohtoKanto/Route 15/Teacher Colette", --Trainersanity
	[1501] = "@JohtoKanto/Route 15/Teacher Hillary", --Trainersanity
	[1502] = "@JohtoKanto/S.S. Aqua/B1F - Teacher Shirley (Westbound)", --Trainersanity
	[1508] = "@JohtoKanto/Blackthorn City/Dragon's Den B1F - Cool Trainer Darin", --Trainersanity
	[1509] = "@JohtoKanto/Blackthorn City/Dragon's Den B1F - Cool Trainer Cara", --Trainersanity
	[1510] = "@JohtoKanto/Blackthorn City/Dragon's Den B1F - Twins Lea & Pia", --Trainersanity
	[1511] = "@JohtoKanto/Ilex Forest/Bug Catcher Wayne", --Trainersanity
	[1512] = "@JohtoKanto/Route 38/Beauty Olivia", --Trainersanity
	[1515] = "@JohtoKanto/Mount Mortar/1F Inside - Pokemaniac Miller", --Trainersanity
	[1516] = "@JohtoKanto/Mount Mortar/2F - Super Nerd Hugh", --Trainersanity
	[1517] = "@JohtoKanto/Mount Mortar/1F Inside - Super Nerd Markus", --Trainersanity
	[1518] = "@JohtoKanto/Route 6/Pokefan Rex", --Trainersanity
	[1519] = "@JohtoKanto/Route 6/Pokefan Allan", --Trainersanity
	[1526] = "@JohtoKanto/Violet City/Item 1", --Overworld
	[1527] = "@JohtoKanto/Violet City/Item 2", --Overworld
	[1528] = "@JohtoKanto/Lake of Rage/Item 1", --Overworld
	[1529] = "@JohtoKanto/Lake of Rage/Item 2", --Overworld
	[1530] = "@JohtoKanto/Sprout Tower/1F - Item", --Overworld
	[1531] = "@JohtoKanto/Sprout Tower/2F - Item", --Overworld
	[1532] = "@JohtoKanto/Sprout Tower/3F - Item 2", --Overworld
	[1533] = "@JohtoKanto/Sprout Tower/3F - Item 1", --Overworld
	[1534] = "@JohtoKanto/Tin Tower/3F - Item", --Overworld
	[1535] = "@JohtoKanto/Tin Tower/4F - Item 3", --Overworld
	[1536] = "@JohtoKanto/Tin Tower/4F - Item 2", --Overworld
	[1537] = "@JohtoKanto/Tin Tower/4F - Item 1", --Overworld
	[1538] = "@JohtoKanto/Tin Tower/5F - Item", --Overworld
	[1539] = "@JohtoKanto/Tin Tower/7F - Item", --Overworld
	[1540] = "@JohtoKanto/Tin Tower/8F - Item 3", --Overworld
	[1541] = "@JohtoKanto/Tin Tower/8F - Item 2", --Overworld
	[1542] = "@JohtoKanto/Tin Tower/8F - Item 1", --Overworld
	[1543] = "@JohtoKanto/Mahogany Town/Rocket HQ B3F - Item 4", --Overworld
	[1544] = "@JohtoKanto/Goldenrod Underground/Warehouse - Item 3", --Overworld
	[1545] = "@JohtoKanto/Burned Tower/1F - Item", --Overworld
	[1546] = "@JohtoKanto/Burned Tower/B1F - Item", --Overworld
	[1547] = "@JohtoKanto/National Park/Item 1", --Overworld
	[1548] = "@JohtoKanto/National Park/Item 2", --Overworld
	[1549] = "@JohtoKanto/Union Cave/1F - Item 2", --Overworld
	[1550] = "@JohtoKanto/Union Cave/1F - Item 4", --Overworld
	[1551] = "@JohtoKanto/Union Cave/1F - Item 3", --Overworld
	[1552] = "@JohtoKanto/Union Cave/1F - Item 1", --Overworld
	[1553] = "@JohtoKanto/Union Cave/B1F - Item 1", --Overworld
	[1554] = "@JohtoKanto/Union Cave/B1F - Item 2", --Overworld
	[1555] = "@JohtoKanto/Union Cave/B2F - Item 1", --Overworld
	[1556] = "@JohtoKanto/Union Cave/B2F - Item 2", --Overworld
	[1557] = "@JohtoKanto/Slowpoke Well/B1F - Item 1", --Overworld
	[1558] = "@JohtoKanto/Slowpoke Well/B2F - Item 1", --Overworld
	[1559] = "@JohtoKanto/Olivine Lighthouse/3F - Item", --Overworld
	[1560] = "@JohtoKanto/Olivine Lighthouse/5F - Item 1", --Overworld
	[1561] = "@JohtoKanto/Olivine Lighthouse/5F - Item 2", --Overworld
	[1562] = "@JohtoKanto/Olivine Lighthouse/5F - Item 3", --Overworld
	[1563] = "@JohtoKanto/Olivine Lighthouse/6F - Item", --Overworld
	[1564] = "@JohtoKanto/Mahogany Town/Rocket HQ B1F - Item 2", --Overworld
	[1565] = "@JohtoKanto/Mahogany Town/Rocket HQ B1F - Item 3", --Overworld
	[1566] = "@JohtoKanto/Mahogany Town/Rocket HQ B1F - Item 1", --Overworld
	[1567] = "@JohtoKanto/Mahogany Town/Rocket HQ B2F - Item", --Overworld
	[1568] = "@JohtoKanto/Mahogany Town/Rocket HQ B3F - Item 3", --Overworld
	[1569] = "@JohtoKanto/Mahogany Town/Rocket HQ B3F - Item 5", --Overworld
	[1570] = "@JohtoKanto/Mahogany Town/Rocket HQ B3F - Item 1", --Overworld
	[1571] = "@JohtoKanto/Mahogany Town/Rocket HQ B3F - Item 2", --Overworld
	[1572] = "@JohtoKanto/Ilex Forest/Item 3", --Overworld
	[1573] = "@JohtoKanto/Goldenrod Underground/Item 1", --Overworld
	[1574] = "@JohtoKanto/Goldenrod Underground/B2F - Item 2", --Overworld
	[1575] = "@JohtoKanto/Goldenrod Underground/B2F - Item 1", --Overworld
	[1576] = "@JohtoKanto/Goldenrod City/Dept. Store B1F - South Item", --Overworld
	[1577] = "@JohtoKanto/Goldenrod City/Dept. Store B1F - Item Behind Card Key Door", --Overworld
	[1578] = "@JohtoKanto/Goldenrod City/Dept. Store B1F - Northwest Item", --Overworld
	[1579] = "@JohtoKanto/Goldenrod City/Dept. Store B1F - Southeast Item", --Overworld
	[1580] = "@JohtoKanto/Goldenrod Underground/Warehouse - Item 1", --Overworld
	[1581] = "@JohtoKanto/Goldenrod Underground/Warehouse - Item 2", --Overworld
	[1582] = "@JohtoKanto/Mount Mortar/1F Outside - Item Up West Ladder", --Overworld
	[1583] = "@JohtoKanto/Mount Mortar/1F Outside - Item Up East Ladder", --Overworld
	[1584] = "@JohtoKanto/Mount Mortar/1F Inside - Item 1", --Overworld
	[1585] = "@JohtoKanto/Mount Mortar/1F Inside - Item 5", --Overworld
	[1586] = "@JohtoKanto/Mount Mortar/1F Inside - Item 2", --Overworld
	[1587] = "@JohtoKanto/Mount Mortar/2F - Item 4", --Overworld
	[1588] = "@JohtoKanto/Mount Mortar/2F - Item 5", --Overworld
	[1589] = "@JohtoKanto/Mount Mortar/2F - Item 6", --Overworld
	[1590] = "@JohtoKanto/Mount Mortar/2F - Item 1", --Overworld
	[1591] = "@JohtoKanto/Mount Mortar/2F - Item 2", --Overworld
	[1592] = "@JohtoKanto/Mount Mortar/2F - Item 3", --Overworld
	[1593] = "@JohtoKanto/Mount Mortar/B1F - Item 3", --Overworld
	[1594] = "@JohtoKanto/Mount Mortar/B1F - Item 1", --Overworld
	[1595] = "@JohtoKanto/Ice Path/1F - HM07 in Itemball", --HM
	[1596] = "@JohtoKanto/Ice Path/1F - Item 1", --Overworld
	[1597] = "@JohtoKanto/Ice Path/B1F - Item", --Overworld
	[1598] = "@JohtoKanto/Ice Path/B2F - Item 2", --Overworld
	[1599] = "@JohtoKanto/Ice Path/B2F - Item 1", --Overworld
	[1600] = "@JohtoKanto/Ice Path/B2F - Item 3", --Overworld
	[1601] = "@JohtoKanto/Ice Path/B3F - Item", --Overworld
	[1602] = "@JohtoKanto/Whirl Islands/1F - Item in Northeast", --Overworld
	[1603] = "@JohtoKanto/Whirl Islands/1F - Item in Southwest", --Overworld
	[1604] = "@JohtoKanto/Whirl Islands/B1F - Item 4", --Overworld
	[1605] = "@JohtoKanto/Whirl Islands/B1F - Item 2", --Overworld
	[1606] = "@JohtoKanto/Whirl Islands/B1F - Item 1", --Overworld
	[1607] = "@JohtoKanto/Whirl Islands/B1F - Item 5", --Overworld
	[1608] = "@JohtoKanto/Whirl Islands/B1F - Item 3", --Overworld
	[1609] = "@JohtoKanto/Whirl Islands/B2F - Item 1", --Overworld
	[1610] = "@JohtoKanto/Whirl Islands/B2F - Item 3", --Overworld
	[1611] = "@JohtoKanto/Whirl Islands/B2F - Item 2", --Overworld
	[1612] = "@JohtoKanto/Silver Cave/1F - Item 2", --Overworld
	[1613] = "@JohtoKanto/Silver Cave/1F - Item 3", --Overworld
	[1614] = "@JohtoKanto/Silver Cave/1F - Item 1", --Overworld
	[1615] = "@JohtoKanto/Silver Cave/2F - Chambers Item 2", --Overworld
	[1616] = "@JohtoKanto/Silver Cave/2F - Chambers Item 1", --Overworld
	[1617] = "@JohtoKanto/Dark Cave Violet Entrance/Item 4", --Overworld
	[1618] = "@JohtoKanto/Dark Cave Violet Entrance/Item 2", --Overworld
	[1619] = "@JohtoKanto/Dark Cave Violet Entrance/Item 3", --Overworld
	[1620] = "@JohtoKanto/Dark Cave Blackthorn Entrance/Item 1", --Overworld
	[1621] = "@JohtoKanto/Dark Cave Blackthorn Entrance/Item 2", --Overworld
	[1622] = "@JohtoKanto/Victory Road/2F - Item 3", --Overworld
	[1623] = "@JohtoKanto/Victory Road/1F - Item 2", --Overworld
	[1624] = "@JohtoKanto/Victory Road/2F - Item 1", --Overworld
	[1625] = "@JohtoKanto/Victory Road/1F - Item 1", --Overworld
	[1626] = "@JohtoKanto/Victory Road/2F - Item 2", --Overworld
	[1627] = "@JohtoKanto/Blackthorn City/Dragon's Den B1F - Item 2", --Overworld
	[1628] = "@JohtoKanto/Route 27/Tohjo Falls - Item", --Overworld
	[1629] = "@JohtoKanto/Route 26/Item", --Overworld
	[1630] = "@JohtoKanto/Route 27/Item 2", --Overworld
	[1631] = "@JohtoKanto/Route 27/Item 1", --Overworld
	[1632] = "@JohtoKanto/Route 29/Item", --Overworld
	[1633] = "@JohtoKanto/Route 31/Item 2", --Overworld
	[1634] = "@JohtoKanto/Route 31/Item 1", --Overworld
	[1635] = "@JohtoKanto/Route 32/Item 1", --Overworld
	[1636] = "@JohtoKanto/Route 32/Item 2", --Overworld
	[1637] = "@JohtoKanto/Route 35/Item", --Overworld
	[1638] = "@JohtoKanto/Route 42/Item 2", --Overworld
	[1639] = "@JohtoKanto/Route 42/Item 1", --Overworld
	[1640] = "@JohtoKanto/Route 43/Item", --Overworld
	[1641] = "@JohtoKanto/Route 44/Item 2", --Overworld
	[1642] = "@JohtoKanto/Route 44/Item 3", --Overworld
	[1643] = "@JohtoKanto/Route 45/Item 3", --Overworld
	[1644] = "@JohtoKanto/Route 45/Item 4", --Overworld
	[1645] = "@JohtoKanto/Route 45/Item 1", --Overworld
	[1646] = "@JohtoKanto/Route 45/Item 2", --Overworld
	[1647] = "@JohtoKanto/Route 46/Item", --Overworld
	[1841] = "@JohtoKanto/Saffron City/Fighting Dojo - Item", --Overworld
	[1842] = "@JohtoKanto/Rock Tunnel/1F - Item 1", --Overworld
	[1843] = "@JohtoKanto/Rock Tunnel/1F - Item 2", --Overworld
	[1844] = "@JohtoKanto/Rock Tunnel/B1F - Item 1", --Overworld
	[1845] = "@JohtoKanto/Rock Tunnel/B1F - Item 2", --Overworld
	[1846] = "@JohtoKanto/Rock Tunnel/B1F - Item 3", --Overworld
	[1847] = "@JohtoKanto/Route 2/Item 2", --Overworld
	[1848] = "@JohtoKanto/Route 2/Item 4", --Overworld
	[1849] = "@JohtoKanto/Route 2/Item 1", --Overworld
	[1850] = "@JohtoKanto/Route 2/Item 3", --Overworld
	[1851] = "@JohtoKanto/Route 4/Item", --Overworld
	[1852] = "@JohtoKanto/Route 12/Item 1", --Overworld
	[1853] = "@JohtoKanto/Route 12/Item 2", --Overworld
	[1854] = "@JohtoKanto/Route 15/Item", --Overworld
	[1855] = "@JohtoKanto/Route 25/Item Behind Cut Tree", --Overworld
	[1864] = "@JohtoKanto/Ruins of Alph/Ho-oh Room - Ho-Oh Room Item 2", --Overworld
	[1865] = "@JohtoKanto/Ruins of Alph/Ho-oh Room - Ho-Oh Room Item 3", --Overworld
	[1866] = "@JohtoKanto/Ruins of Alph/Ho-oh Room - Ho-Oh Room Item 4", --Overworld
	[1867] = "@JohtoKanto/Ruins of Alph/Ho-oh Room - Ho-Oh Room Item 1", --Overworld
	[1868] = "@JohtoKanto/Ruins of Alph/Kabuto Room - Kabuto Room Item 1", --Overworld
	[1869] = "@JohtoKanto/Ruins of Alph/Kabuto Room - Kabuto Room Item 4", --Overworld
	[1870] = "@JohtoKanto/Ruins of Alph/Kabuto Room - Kabuto Room Item 3", --Overworld
	[1871] = "@JohtoKanto/Ruins of Alph/Kabuto Room - Kabuto Room Item 2", --Overworld
	[1872] = "@JohtoKanto/Ruins of Alph/Omanyte Room - Omanyte Room Item 1", --Overworld
	[1873] = "@JohtoKanto/Ruins of Alph/Omanyte Room - Omanyte Room Item 2", --Overworld
	[1874] = "@JohtoKanto/Ruins of Alph/Omanyte Room - Omanyte Room Item 4", --Overworld
	[1875] = "@JohtoKanto/Ruins of Alph/Omanyte Room - Omanyte Room Item 3", --Overworld
	[1876] = "@JohtoKanto/Ruins of Alph/Aerodactyl Room - Aerodactyl Room Item 2", --Overworld
	[1877] = "@JohtoKanto/Ruins of Alph/Aerodactyl Room - Aerodactyl Room Item 4", --Overworld
	[1878] = "@JohtoKanto/Ruins of Alph/Aerodactyl Room - Aerodactyl Room Item 3", --Overworld
	[1879] = "@JohtoKanto/Ruins of Alph/Aerodactyl Room - Aerodactyl Room Item 1", --Overworld
	[1882] = "@JohtoKanto/Mount Mortar/1F Inside - Item 4", --Overworld
	[1883] = "@JohtoKanto/Mount Mortar/1F Inside - Item 6", --Overworld
	[1900] = "@JohtoKanto/Route 30/Item", --Overworld
	[1901] = "@JohtoKanto/Ilex Forest/Item 4", --Overworld
	[1902] = "@JohtoKanto/Ilex Forest/Item 1", --Overworld
	[1903] = "@JohtoKanto/Ilex Forest/Item 2", --Overworld
	[1904] = "@JohtoKanto/Route 34/Item Across Water", --Overworld
	[1905] = "@JohtoKanto/Route 44/Item 1", --Overworld
	[1906] = "@JohtoKanto/Ice Path/1F - Item 2", --Overworld
	[1907] = "@JohtoKanto/Blackthorn City/Dragon's Den B1F - Item 1", --Overworld
	[1908] = "@JohtoKanto/Blackthorn City/Dragon's Den B1F - Item 3", --Overworld
	[1909] = "@JohtoKanto/Silver Cave/1F - Item 4", --Overworld
	[1910] = "@JohtoKanto/Silver Cave/2F - Item 1", --Overworld
	[1911] = "@JohtoKanto/Silver Cave/2F - Item 3", --Overworld
	[1912] = "@JohtoKanto/Silver Cave/2F - Item 2", --Overworld
	[1914] = "@JohtoKanto/Tin Tower/6F - Item", --Overworld
	[1915] = "@JohtoKanto/Tin Tower/9F - Item", --Overworld
	[1916] = "@JohtoKanto/Mount Mortar/1F Inside - Item 3", --Overworld
	[1917] = "@JohtoKanto/Mount Mortar/1F Inside - Item 7", --Overworld
	[1918] = "@JohtoKanto/Mount Mortar/B1F - Item 2", --Overworld
	[1919] = "@JohtoKanto/Mount Mortar/B1F - Item 4", --Overworld
	[1920] = "@JohtoKanto/Mount Mortar/B1F - Item 5", --Overworld
	[1921] = "@JohtoKanto/Radio Tower/5F - Item", --Overworld
	[1922] = "@JohtoKanto/Dark Cave Violet Entrance/Item 1", --Overworld
}