MAP_MAPPING =	{
	[1] =	{
		[1] =	{"Johto Cities", "Olivine City"},	--OLIVINE_POKECENTER_1F
		[2] =	{"Johto Cities", "Olivine City"},	--OLIVINE_GYM
		[3] =	{"Johto Cities", "Olivine City"},	--OLIVINE_TIMS_HOUSE
		[4] =	{"Johto Cities", "Olivine City"},	--OLIVINE_HOUSE_BETA
		[5] =	{"Johto Cities", "Olivine City"},	--OLIVINE_PUNISHMENT_SPEECH_HOUSE
		[6] =	{"Johto Cities", "Olivine City"},	--OLIVINE_GOOD_ROD_HOUSE
		[7] =	{"Johto Cities", "Olivine City"},	--OLIVINE_CAFE
		[8] =	{"Johto Cities", "Olivine City"},	--OLIVINE_MART
		[9] =	{"Johto Routes", "Route 38"},		--ROUTE_38_ECRUTEAK_GATE
		[10] =	{"Johto Routes", "Route 39"},		--ROUTE_39_BARN
		[11] =	{"Johto Routes", "Route 39"},		--ROUTE_39_FARMHOUSE
		[12] =	{"Johto Routes", "Route 38"},		--ROUTE_38
		[13] =	{"Johto Routes", "Route 39"},		--ROUTE_39
		[14] =	{"Johto Cities", "Olivine City"},	--OLIVINE_CITY
	},
	[2] =	{
		[1] =	{"Johto Cities", "Mahogany Town"},	--MAHOGANY_RED_GYARADOS_SPEECH_HOUSE
		[2] =	{"Johto Cities", "Mahogany Town"},	--MAHOGANY_GYM
		[3] =	{"Johto Cities", "Mahogany Town"},	--MAHOGANY_POKECENTER_1F
		[4] =	{"Johto Routes", "Route 42"},		--ROUTE_42_ECRUTEAK_GATE
		[5] =	{"Johto Routes", "Route 42"},		--ROUTE_42
		[6] =	{"Johto Routes", "Route 44"},		--ROUTE_44
		[7] =	{"Johto Cities", "Mahogany Town"},	--MAHOGANY_TOWN
	},
	[3] =	{
		[1] =	{"Johto Dungeons", "Sprout Tower", "Sprout Tower 1F"},					--SPROUT_TOWER_1F
		[2] =	{"Johto Dungeons", "Sprout Tower", "Sprout Tower 2F"},					--SPROUT_TOWER_2F
		[3] =	{"Johto Dungeons", "Sprout Tower", "Sprout Tower 3F"},					--SPROUT_TOWER_3F
		[4] =	{"Johto Dungeons", "Tin Tower", "Tin Tower 1F"},						--TIN_TOWER_1F
		[5] =	{"Johto Dungeons", "Tin Tower", "Tin Tower 2F"},						--TIN_TOWER_2F
		[6] =	{"Johto Dungeons", "Tin Tower", "Tin Tower 3F"},						--TIN_TOWER_3F
		[7] =	{"Johto Dungeons", "Tin Tower", "Tin Tower 4F"},						--TIN_TOWER_4F
		[8] =	{"Johto Dungeons", "Tin Tower", "Tin Tower 5F"},						--TIN_TOWER_5F
		[9] =	{"Johto Dungeons", "Tin Tower", "Tin Tower 6F"},						--TIN_TOWER_6F
		[10] =	{"Johto Dungeons", "Tin Tower", "Tin Tower 7F"},						--TIN_TOWER_7F
		[11] =	{"Johto Dungeons", "Tin Tower", "Tin Tower 8F"},						--TIN_TOWER_8F
		[12] =	{"Johto Dungeons", "Tin Tower", "Tin Tower 9F"},						--TIN_TOWER_9F
		[13] =	{"Johto Dungeons", "Burned Tower", "Burned Tower 1F"},					--BURNED_TOWER_1F
		[14] =	{"Johto Dungeons", "Burned Tower", "Burned Tower B1F"},					--BURNED_TOWER_B1F
		[15] =	{"Johto Dungeons", "National Park"},									--NATIONAL_PARK
		[16] =	{"Johto Dungeons", "National Park"},									--NATIONAL_PARK_BUG_CONTEST
		[17] =	{"Johto Dungeons", "Radio Tower", "Radio Tower 1F"},					--RADIO_TOWER_1F
		[18] =	{"Johto Dungeons", "Radio Tower", "Radio Tower 2F"},					--RADIO_TOWER_2F
		[19] =	{"Johto Dungeons", "Radio Tower", "Radio Tower 3F"},					--RADIO_TOWER_3F
		[20] =	{"Johto Dungeons", "Radio Tower", "Radio Tower 4F"},					--RADIO_TOWER_4F
		[21] =	{"Johto Dungeons", "Radio Tower", "Radio Tower 5F"},					--RADIO_TOWER_5F
		[22] =	{"Johto Dungeons", "Ruins of Alph"},									--RUINS_OF_ALPH_OUTSIDE
		[23] =	{"Johto Dungeons", "Ruins of Alph"},									--RUINS_OF_ALPH_HO_OH_CHAMBER
		[24] =	{"Johto Dungeons", "Ruins of Alph"},									--RUINS_OF_ALPH_KABUTO_CHAMBER
		[25] =	{"Johto Dungeons", "Ruins of Alph"},									--RUINS_OF_ALPH_OMANYTE_CHAMBER
		[26] =	{"Johto Dungeons", "Ruins of Alph"},									--RUINS_OF_ALPH_AERODACTYL_CHAMBER
		[27] =	{"Johto Dungeons", "Ruins of Alph"},									--RUINS_OF_ALPH_INNER_CHAMBER
		[28] =	{"Johto Dungeons", "Ruins of Alph"},									--RUINS_OF_ALPH_RESEARCH_CENTER
		[29] =	{"Johto Dungeons", "Ruins of Alph"},									--RUINS_OF_ALPH_HO_OH_ITEM_ROOM
		[30] =	{"Johto Dungeons", "Ruins of Alph"},									--RUINS_OF_ALPH_KABUTO_ITEM_ROOM
		[31] =	{"Johto Dungeons", "Ruins of Alph"},									--RUINS_OF_ALPH_OMANYTE_ITEM_ROOM
		[32] =	{"Johto Dungeons", "Ruins of Alph"},									--RUINS_OF_ALPH_AERODACTYL_ITEM_ROOM
		[33] =	{"Johto Dungeons", "Ruins of Alph"},									--RUINS_OF_ALPH_HO_OH_WORD_ROOM
		[34] =	{"Johto Dungeons", "Ruins of Alph"},									--RUINS_OF_ALPH_KABUTO_WORD_ROOM
		[35] =	{"Johto Dungeons", "Ruins of Alph"},									--RUINS_OF_ALPH_OMANYTE_WORD_ROOM
		[36] =	{"Johto Dungeons", "Ruins of Alph"},									--RUINS_OF_ALPH_AERODACTYL_WORD_ROOM
		[37] =	{"Johto Dungeons", "Union Cave", "Union Cave 1F"},						--UNION_CAVE_1F
		[38] =	{"Johto Dungeons", "Union Cave", "Union Cave B1F"},						--UNION_CAVE_B1F
		[39] =	{"Johto Dungeons", "Union Cave", "Union Cave B2F"},						--UNION_CAVE_B2F
		[40] =	{"Johto Dungeons", "Slowpoke Well", "Slowpoke Well B1F"},				--SLOWPOKE_WELL_B1F
		[41] =	{"Johto Dungeons", "Slowpoke Well", "Slowpoke Well B2F"},				--SLOWPOKE_WELL_B2F
		[42] =	{"Johto Dungeons", "Olivine Lighthouse", "Olivine Lighthouse 1F"},		--OLIVINE_LIGHTHOUSE_1F
		[43] =	{"Johto Dungeons", "Olivine Lighthouse", "Olivine Lighthouse 2F"},		--OLIVINE_LIGHTHOUSE_2F
		[44] =	{"Johto Dungeons", "Olivine Lighthouse", "Olivine Lighthouse 3F"},		--OLIVINE_LIGHTHOUSE_3F
		[45] =	{"Johto Dungeons", "Olivine Lighthouse", "Olivine Lighthouse 4F"},		--OLIVINE_LIGHTHOUSE_4F
		[46] =	{"Johto Dungeons", "Olivine Lighthouse", "Olivine Lighthouse 5F"},		--OLIVINE_LIGHTHOUSE_5F
		[47] =	{"Johto Dungeons", "Olivine Lighthouse", "Olivine Lighthouse 6F"},		--OLIVINE_LIGHTHOUSE_6F
		[48] =	{"Johto Cities", "Mahogany Town"},										--MAHOGANY_MART_1F
		[49] =	{"Johto Dungeons", "Rocket HQ", "Rocket HQ B1F"},						--TEAM_ROCKET_BASE_B1F
		[50] =	{"Johto Dungeons", "Rocket HQ", "Rocket HQ B2F"},						--TEAM_ROCKET_BASE_B2F
		[51] =	{"Johto Dungeons", "Rocket HQ", "Rocket HQ B3F"},						--TEAM_ROCKET_BASE_B3F
		[52] =	{"Johto Dungeons", "Ilex Forest"},										--ILEX_FOREST
		[53] =	{"Johto Dungeons", "Goldenrod Underground", "Underground B1F"},			--GOLDENROD_UNDERGROUND
		[54] =	{"Johto Dungeons", "Goldenrod Underground", "Underground B2F"},			--GOLDENROD_UNDERGROUND_SWITCH_ROOM_ENTRANCES
		[55] =	{"Johto Dungeons", "Goldenrod Underground", "Dept. Store B1F"},			--GOLDENROD_DEPT_STORE_B1F
		[56] =	{"Johto Dungeons", "Goldenrod Underground", "Underground Warehouse"},	--GOLDENROD_UNDERGROUND_WAREHOUSE
		[57] =	{"Johto Dungeons", "Mount Mortar", "Mount Mortar 1F Outside"},			--MOUNT_MORTAR_1F_OUTSIDE
		[58] =	{"Johto Dungeons", "Mount Mortar", "Mount Mortar 1F Inside"},			--MOUNT_MORTAR_1F_INSIDE
		[59] =	{"Johto Dungeons", "Mount Mortar", "Mount Mortar 2F"},					--MOUNT_MORTAR_2F_INSIDE
		[60] =	{"Johto Dungeons", "Mount Mortar", "Mount Mortar B1F"},					--MOUNT_MORTAR_B1F
		[61] =	{"Johto Dungeons", "Ice Path", "Ice Path 1F"},							--ICE_PATH_1F
		[62] =	{"Johto Dungeons", "Ice Path", "Ice Path B1F"},							--ICE_PATH_B1F
		[63] =	{"Johto Dungeons", "Ice Path", "Ice Path B2F - Mahogany Side"},			--ICE_PATH_B2F_MAHOGANY_SIDE
		[64] =	{"Johto Dungeons", "Ice Path", "Ice Path B2F - Blackthorn Side"},		--ICE_PATH_B2F_BLACKTHORN_SIDE
		[65] =	{"Johto Dungeons", "Ice Path", "Ice Path B3F"},							--ICE_PATH_B3F
		[66] =	{"Johto Dungeons", "Whirl Islands", "Whirl Islands B1F"},				--WHIRL_ISLAND_NW
		[67] =	{"Johto Dungeons", "Whirl Islands", "Whirl Islands NE"},				--WHIRL_ISLAND_NE
		[68] =	{"Johto Dungeons", "Whirl Islands", "Whirl Islands SW"},				--WHIRL_ISLAND_SW
		[69] =	{"Johto Dungeons", "Whirl Islands", "Whirl Islands B1F"},				--WHIRL_ISLAND_CAVE
		[70] =	{"Johto Dungeons", "Whirl Islands", "Whirl Islands Se"},				--WHIRL_ISLAND_SE
		[71] =	{"Johto Dungeons", "Whirl Islands", "Whirl Islands B1F"},				--WHIRL_ISLAND_B1F
		[72] =	{"Johto Dungeons", "Whirl Islands", "Whirl Islands B2F"},				--WHIRL_ISLAND_B2F
		[73] =	{"Johto Dungeons", "Whirl Islands", "Whirl Islands B2F"},				--WHIRL_ISLAND_LUGIA_CHAMBER
		[74] =	{"Kanto Dungeons", "Silver Cave", "Silver Cave 1F"},					--SILVER_CAVE_ROOM_1
		[75] =	{"Kanto Dungeons", "Silver Cave", "Silver Cave 2F"},					--SILVER_CAVE_ROOM_2
		[76] =	{"Kanto Dungeons", "Silver Cave", "Silver Cave 3F"},					--SILVER_CAVE_ROOM_3
		[77] =	{"Kanto Dungeons", "Silver Cave", "Silver Cave 2F"},					--SILVER_CAVE_ITEM_ROOMS
		[78] =	{"Johto Dungeons", "Dark Cave", "Dark Cave - Violet Entrance"},			--DARK_CAVE_VIOLET_ENTRANCE
		[79] =	{"Johto Dungeons", "Dark Cave", "Dark Cave - Blackthorn Entrance"},		--DARK_CAVE_BLACKTHORN_ENTRANCE
		[80] =	{"Johto Dungeons", "Dragons Den"},										--DRAGONS_DEN_1F
		[81] =	{"Johto Dungeons", "Dragons Den"},										--DRAGONS_DEN_B1F
		[82] =	{"Johto Dungeons", "Dragons Den"},										--DRAGON_SHRINE
		[83] =	{"Kanto Routes", "Route 27"},											--TOHJO_FALLS
		[84] =	{"Kanto Dungeons", "Digletts Cave"},									--DIGLETTS_CAVE
		[85] =	{"Kanto Routes", "Route 3"},											--MOUNT_MOON
		[86] =	{"Kanto Dungeons", "Underground Path"},									--UNDERGROUND_PATH
		[87] =	{"Kanto Dungeons", "Rock Tunnel", "Rock Tunnel 1F"},					--ROCK_TUNNEL_1F
		[88] =	{"Kanto Dungeons", "Rock Tunnel", "Rock Tunnel B1F"},					--ROCK_TUNNEL_B1F
		[89] =	{"Kanto Cities", "Fuchsia City"},										--SAFARI_ZONE_FUCHSIA_GATE_BETA
		[90] =	{"Kanto Cities", "Fuchsia City"},										--SAFARI_ZONE_BETA
		[91] =	{"Kanto Dungeons", "Victory Road"},										--VICTORY_ROAD
	},
	[4] =	{
		[1] =	{"Johto Cities", "Ecruteak City"},	--ECRUTEAK_TIN_TOWER_ENTRANCE
		[2] =	{"Johto Cities", "Ecruteak City"},	--WISE_TRIOS_ROOM
		[3] =	{"Johto Cities", "Ecruteak City"},	--ECRUTEAK_POKECENTER_1F
		[4] =	{"Johto Cities", "Ecruteak City"},	--ECRUTEAK_LUGIA_SPEECH_HOUSE
		[5] =	{"Johto Cities", "Ecruteak City"},	--DANCE_THEATER
		[6] =	{"Johto Cities", "Ecruteak City"},	--ECRUTEAK_MART
		[7] =	{"Johto Cities", "Ecruteak City"},	--ECRUTEAK_GYM
		[8] =	{"Johto Cities", "Ecruteak City"},	--ECRUTEAK_ITEMFINDER_HOUSE
		[9] =	{"Johto Cities", "Ecruteak City"},	--ECRUTEAK_CITY
	},
	[5] =	{
		[1] =	{"Johto Cities", "Blackthorn City"},	--BLACKTHORN_GYM_1F
		[2] =	{"Johto Cities", "Blackthorn City"},	--BLACKTHORN_GYM_2F
		[3] =	{"Johto Cities", "Blackthorn City"},	--BLACKTHORN_DRAGON_SPEECH_HOUSE
		[4] =	{"Johto Cities", "Blackthorn City"},	--BLACKTHORN_EMYS_HOUSE
		[5] =	{"Johto Cities", "Blackthorn City"},	--BLACKTHORN_MART
		[6] =	{"Johto Cities", "Blackthorn City"},	--BLACKTHORN_POKECENTER_1F
		[7] =	{"Johto Cities", "Blackthorn City"},	--MOVE_DELETERS_HOUSE
		[8] =	{"Johto Routes", "Route 45"},			--ROUTE_45
		[9] =	{"Johto Routes", "Route 46"},			--ROUTE_46
		[10] =	{"Johto Cities", "Blackthorn City"},	--BLACKTHORN_CITY
	},
	[6] =	{
		[1] =	{"Kanto Cities", "Cinnabar Island"},	--CINNABAR_POKECENTER_1F
		[2] =	{"Kanto Cities", "Cinnabar Island"},	--CINNABAR_POKECENTER_2F_BETA
		[3] =	{"Kanto Routes", "Route 19"},			--ROUTE_19_FUCHSIA_GATE
		[4] =	{"Kanto Routes", "Route 20"},			--SEAFOAM_GYM
		[5] =	{"Kanto Routes", "Route 19"},			--ROUTE_19
		[6] =	{"Kanto Routes", "Route 20"},			--ROUTE_20
		[7] =	{"Kanto Routes", "Route 21"},			--ROUTE_21
		[8] =	{"Kanto Cities", "Cinnabar Island"},	--CINNABAR_ISLAND
	},
	[7] =	{
		[1] =	{"Kanto Cities", "Cerulean City"},	--CERULEAN_GYM_BADGE_SPEECH_HOUSE
		[2] =	{"Kanto Cities", "Cerulean City"},	--CERULEAN_POLICE_STATION
		[3] =	{"Kanto Cities", "Cerulean City"},	--CERULEAN_TRADE_SPEECH_HOUSE
		[4] =	{"Kanto Cities", "Cerulean City"},	--CERULEAN_POKECENTER_1F
		[5] =	{"Kanto Cities", "Cerulean City"},	--CERULEAN_POKECENTER_2F_BETA
		[6] =	{"Kanto Cities", "Cerulean City"},	--CERULEAN_GYM
		[7] =	{"Kanto Cities", "Cerulean City"},	--CERULEAN_MART
		[8] =	{"Kanto Routes", "Route 10"},		--ROUTE_10_POKECENTER_1F
		[9] =	{"Kanto Routes", "Route 10"},		--ROUTE_10_POKECENTER_2F_BETA
		[10] =	{"Kanto Dungeons", "Power Plant"},	--POWER_PLANT
		[11] =	{"Kanto Routes", "Route 25"},		--BILLS_HOUSE
		[12] =	{"Kanto Routes", "Route 4"},		--ROUTE_4
		[13] =	{"Kanto Routes", "Route 9"},		--ROUTE_9
		[14] =	{"Kanto Routes", "Route 10"},		--ROUTE_10_NORTH
		[15] =	{"Kanto Routes", "Route 24"},		--ROUTE_24
		[16] =	{"Kanto Routes", "Route 25"},		--ROUTE_25
		[17] =	{"Kanto Cities", "Cerulean City"},	--CERULEAN_CITY
	},
	[8] =	{
		[1] =	{"Johto Cities", "Azalea Town"},	--AZALEA_POKECENTER_1F
		[2] =	{"Johto Cities", "Azalea Town"},	--CHARCOAL_KILN
		[3] =	{"Johto Cities", "Azalea Town"},	--AZALEA_MART
		[4] =	{"Johto Cities", "Azalea Town"},	--KURTS_HOUSE
		[5] =	{"Johto Cities", "Azalea Town"},	--AZALEA_GYM
		[6] =	{"Johto Routes", "Route 33"},		--ROUTE_33
		[7] =	{"Johto Cities", "Azalea Town"},	--AZALEA_TOWN
	},
	[9] =	{
		[1] =	{"Johto Routes", "Lake of Rage"},	--LAKE_OF_RAGE_HIDDEN_POWER_HOUSE
		[2] =	{"Johto Routes", "Lake of Rage"},	--LAKE_OF_RAGE_MAGIKARP_HOUSE
		[3] =	{"Johto Routes", "Route 43"},		--ROUTE_43_MAHOGANY_GATE
		[4] =	{"Johto Routes", "Route 43"},		--ROUTE_43_GATE
		[5] =	{"Johto Routes", "Route 43"},		--ROUTE_43
		[6] =	{"Johto Routes", "Lake of Rage"},	--LAKE_OF_RAGE
	},
	[10] =	{
		[1] =	{"Johto Routes", "Route 32"},		--ROUTE_32
		[2] =	{"Johto Routes", "Route 35"},		--ROUTE_35
		[3] =	{"Johto Routes", "Route 36"},		--ROUTE_36
		[4] =	{"Johto Routes", "Route 37"},		--ROUTE_37
		[5] =	{"Johto Cities", "Violet City"},	--VIOLET_CITY
		[6] =	{"Johto Cities", "Violet City"},	--VIOLET_MART
		[7] =	{"Johto Cities", "Violet City"},	--VIOLET_GYM
		[8] =	{"Johto Cities", "Violet City"},	--EARLS_POKEMON_ACADEMY
		[9] =	{"Johto Cities", "Violet City"},	--VIOLET_NICKNAME_SPEECH_HOUSE
		[10] =	{"Johto Cities", "Violet City"},	--VIOLET_POKECENTER_1F
		[11] =	{"Johto Cities", "Violet City"},	--VIOLET_KYLES_HOUSE
		[12] =	{"Johto Routes", "Route 32"},		--ROUTE_32_RUINS_OF_ALPH_GATE
		[13] =	{"Johto Routes", "Route 32"},		--ROUTE_32_POKECENTER_1F
		[14] =	{"Johto Routes", "Route 35"},		--ROUTE_35_GOLDENROD_GATE
		[15] =	{"Johto Routes", "Route 35"},		--ROUTE_35_NATIONAL_PARK_GATE
		[16] =	{"Johto Routes", "Route 36"},		--ROUTE_36_RUINS_OF_ALPH_GATE
		[17] =	{"Johto Routes", "Route 36"},		--ROUTE_36_NATIONAL_PARK_GATE
	},
	[11] =	{
		[1] =	{"Johto Routes", "Route 34"},		--ROUTE_34
		[2] =	{"Johto Cities", "Goldenrod City"},	--GOLDENROD_CITY
		[3] =	{"Johto Cities", "Goldenrod City"},	--GOLDENROD_GYM
		[4] =	{"Johto Cities", "Goldenrod City"},	--GOLDENROD_BIKE_SHOP
		[5] =	{"Johto Cities", "Goldenrod City"},	--GOLDENROD_HAPPINESS_RATER
		[6] =	{"Johto Cities", "Goldenrod City"},	--BILLS_FAMILYS_HOUSE
		[7] =	{"Johto Cities", "Goldenrod City"},	--GOLDENROD_MAGNET_TRAIN_STATION
		[8] =	{"Johto Cities", "Goldenrod City"},	--GOLDENROD_FLOWER_SHOP
		[9] =	{"Johto Cities", "Goldenrod City"},	--GOLDENROD_PP_SPEECH_HOUSE
		[10] =	{"Johto Cities", "Goldenrod City"},	--GOLDENROD_NAME_RATER
		[11] =	{"Johto Cities", "Goldenrod City"},	--GOLDENROD_DEPT_STORE_1F
		[12] =	{"Johto Cities", "Goldenrod City"},	--GOLDENROD_DEPT_STORE_2F
		[13] =	{"Johto Cities", "Goldenrod City"},	--GOLDENROD_DEPT_STORE_3F
		[14] =	{"Johto Cities", "Goldenrod City"},	--GOLDENROD_DEPT_STORE_4F
		[15] =	{"Johto Cities", "Goldenrod City"},	--GOLDENROD_DEPT_STORE_5F
		[16] =	{"Johto Cities", "Goldenrod City"},	--GOLDENROD_DEPT_STORE_6F
		[17] =	{"Johto Cities", "Goldenrod City"},	--GOLDENROD_DEPT_STORE_ELEVATOR
		[18] =	{"Johto Cities", "Goldenrod City"},	--GOLDENROD_DEPT_STORE_ROOF
		[19] =	{"Johto Cities", "Goldenrod City"},	--GOLDENROD_GAME_CORNER
		[20] =	{"Johto Cities", "Goldenrod City"},	--GOLDENROD_POKECENTER_1F
		[21] =	{"Johto Cities", "Goldenrod City"},	--POKECOM_CENTER_ADMIN_OFFICE_MOBILE
		[22] =	{"Johto Dungeons", "Ilex Forest"},	--ILEX_FOREST_AZALEA_GATE
		[23] =	{"Johto Routes", "Route 34"},		--ROUTE_34_ILEX_FOREST_GATE
		[24] =	{"Johto Routes", "Route 34"},		--DAY_CARE
	},
	[12] =	{

		[1] =	{"Kanto Routes", "Route 6"},		--ROUTE_6
		[2] =	{"Kanto Routes", "Route 11"},		--ROUTE_11
		[3] =	{"Kanto Cities", "Vermilion City"},	--VERMILION_CITY
		[4] =	{"Kanto Cities", "Vermilion City"},	--VERMILION_FISHING_SPEECH_HOUSE
		[5] =	{"Kanto Cities", "Vermilion City"},	--VERMILION_POKECENTER_1F
		[6] =	{"Kanto Cities", "Vermilion City"},	--VERMILION_POKECENTER_2F_BETA
		[7] =	{"Kanto Cities", "Vermilion City"},	--POKEMON_FAN_CLUB
		[8] =	{"Kanto Cities", "Vermilion City"},	--VERMILION_MAGNET_TRAIN_SPEECH_HOUSE
		[9] =	{"Kanto Cities", "Vermilion City"},	--VERMILION_MART
		[10] =	{"Kanto Cities", "Vermilion City"},	--VERMILION_DIGLETTS_CAVE_SPEECH_HOUSE
		[11] =	{"Kanto Cities", "Vermilion City"},	--VERMILION_GYM
		[12] =	{"Kanto Routes", "Route 6"},		--ROUTE_6_SAFFRON_GATE
		[13] =	{"Kanto Routes", "Route 6"},		--ROUTE_6_UNDERGROUND_PATH_ENTRANCE
	
	},
	[13] =	{
		[1] =	{"Kanto Routes", "Route 1"},	--ROUTE_1
		[2] =	{"Kanto Routes", "Route 1"},	--PALLET_TOWN
		[3] =	{"Kanto Routes", "Route 1"},	--REDS_HOUSE_1F
		[4] =	{"Kanto Routes", "Route 1"},	--REDS_HOUSE_2F
		[5] =	{"Kanto Routes", "Route 1"},	--BLUES_HOUSE
		[6] =	{"Kanto Routes", "Route 1"},	--OAKS_LAB
	},
	[14] =	{
		[1] =	{"Kanto Routes", "Route 3"},		--ROUTE_3
		[2] =	{"Kanto Cities", "Pewter City"},	--PEWTER_CITY
		[3] =	{"Kanto Cities", "Pewter City"},	--PEWTER_NIDORAN_SPEECH_HOUSE
		[4] =	{"Kanto Cities", "Pewter City"},	--PEWTER_GYM
		[5] =	{"Kanto Cities", "Pewter City"},	--PEWTER_MART
		[6] =	{"Kanto Cities", "Pewter City"},	--PEWTER_POKECENTER_1F
		[7] =	{"Kanto Cities", "Pewter City"},	--PEWTER_POKECENTER_2F_BETA
		[8] =	{"Kanto Cities", "Pewter City"},	--PEWTER_SNOOZE_SPEECH_HOUSE
	},
	[15] =	{
		[1] =	{"Fast Ship", "Fast Ship 1F"},				--OLIVINE_PORT
		[2] =	{"Fast Ship", "Fast Ship 1F"},				--VERMILION_PORT
		[3] =	{"Fast Ship", "Fast Ship 1F"},				--FAST_SHIP_1F
		[4] =	{"Fast Ship", "Fast Ship 1F - Cabins 1"},	--FAST_SHIP_CABINS_NNW_NNE_NE
		[5] =	{"Fast Ship", "Fast Ship 1F - Cabins 3"},	--FAST_SHIP_CABINS_SW_SSW_NW
		[6] =	{"Fast Ship", "Fast Ship 1F - Cabins 2"},	--FAST_SHIP_CABINS_SE_SSE_CAPTAINS_CABIN
		[7] =	{"Fast Ship", "Fast Ship B1F"},				--FAST_SHIP_B1F
		[8] =	{"Fast Ship", "Fast Ship 1F"}, 				--OLIVINE_PORT_PASSAGE
		[9] =	{"Fast Ship", "Fast Ship 1F"},				--VERMILION_PORT_PASSAGE
		[10] =	{},											--MOUNT_MOON_SQUARE
		[11] =	{},											--MOUNT_MOON_GIFT_SHOP
		[12] =	{},											--TIN_TOWER_ROOF
	},
	[16] =	{
		[1] =	{},	--ROUTE_23
		[2] =	{},	--INDIGO_PLATEAU_POKECENTER_1F
		[3] =	{},	--WILLS_ROOM
		[4] =	{},	--KOGAS_ROOM
		[5] =	{},	--BRUNOS_ROOM
		[6] =	{},	--KARENS_ROOM
		[7] =	{},	--LANCES_ROOM
		[8] =	{},	--HALL_OF_FAME
	},
	[17] =	{
		[1] =	{"Kanto Routes", "Route 13"},		--ROUTE_13
		[2] =	{"Kanto Routes", "Route 14"},		--ROUTE_14
		[3] =	{"Kanto Routes", "Route 15"},		--ROUTE_15
		[4] =	{"Kanto Routes", "Route 18"},		--ROUTE_18
		[5] =	{"Kanto Cities", "Fuchsia City"},	--FUCHSIA_CITY
		[6] =	{"Kanto Cities", "Fuchsia City"},	--FUCHSIA_MART
		[7] =	{"Kanto Cities", "Fuchsia City"},	--SAFARI_ZONE_MAIN_OFFICE
		[8] =	{"Kanto Cities", "Fuchsia City"},	--FUCHSIA_GYM
		[9] =	{"Kanto Cities", "Fuchsia City"},	--BILLS_BROTHERS_HOUSE
		[10] =	{"Kanto Cities", "Fuchsia City"},	--FUCHSIA_POKECENTER_1F
		[11] =	{"Kanto Cities", "Fuchsia City"},	--FUCHSIA_POKECENTER_2F_BETA
		[12] =	{"Kanto Cities", "Fuchsia City"},	--SAFARI_ZONE_WARDENS_HOME
		[13] =	{"Kanto Routes", "Route 15"},		--ROUTE_15_FUCHSIA_GATE
	},
	[18] =	{
		[1] =	{"Kanto Routes", "Route 8"},		--ROUTE_8
		[2] =	{"Kanto Routes", "Route 12"},		--ROUTE_12
		[3] =	{"Kanto Routes", "Route 10"},		--ROUTE_10_SOUTH
		[4] =	{"Kanto Cities", "Lavender Town"},	--LAVENDER_TOWN
		[5] =	{"Kanto Cities", "Lavender Town"},	--LAVENDER_POKECENTER_1F
		[6] =	{"Kanto Cities", "Lavender Town"},	--LAVENDER_POKECENTER_2F_BETA
		[7] =	{"Kanto Cities", "Lavender Town"},	--MR_FUJIS_HOUSE
		[8] =	{"Kanto Cities", "Lavender Town"},	--LAVENDER_SPEECH_HOUSE
		[9] =	{"Kanto Cities", "Lavender Town"},	--LAVENDER_NAME_RATER
		[10] =	{"Kanto Cities", "Lavender Town"},	--LAVENDER_MART
		[11] =	{"Kanto Cities", "Lavender Town"},	--SOUL_HOUSE
		[12] =	{"Kanto Cities", "Lavender Town"},	--LAV_RADIO_TOWER_1F
		[13] =	{"Kanto Routes", "Route 8"},		--ROUTE_8_SAFFRON_GATE
		[14] =	{"Kanto Routes", "Route 12"},		--ROUTE_12_SUPER_ROD_HOUSE
	},
	[19] =	{
		[1] =	{"Kanto Routes", "Route 28"},								--ROUTE_28
		[2] =	{"Kanto Dungeons", "Silver Cave", "Silver Cave Outside"},	--SILVER_CAVE_OUTSIDE
		[3] =	{"Kanto Dungeons", "Silver Cave", "Silver Cave Outside"},	--SILVER_CAVE_POKECENTER_1F
		[4] =	{"Kanto Routes", "Route 28"},								--ROUTE_28_STEEL_WING_HOUSE
	},
	[20] =	{
		[1] =	{},	--POKECENTER_2F
		[2] =	{},	--TRADE_CENTER
		[3] =	{},	--COLOSSEUM
		[4] =	{},	--TIME_CAPSULE
		[5] =	{},	--MOBILE_TRADE_ROOM
		[6] =	{},	--MOBILE_BATTLE_ROOM
	},
	[21] =	{
		[1] =	{"Kanto Routes", "Route 7"},		--ROUTE_7
		[2] =	{"Kanto Routes", "Route 16"},		--ROUTE_16
		[3] =	{"Kanto Routes", "Route 17"},		--ROUTE_17
		[4] =	{"Kanto Cities", "Celadon City"},	--CELADON_CITY
		[5] =	{"Kanto Cities", "Celadon City"},	--CELADON_DEPT_STORE_1F
		[6] =	{"Kanto Cities", "Celadon City"},	--CELADON_DEPT_STORE_2F
		[7] =	{"Kanto Cities", "Celadon City"},	--CELADON_DEPT_STORE_3F
		[8] =	{"Kanto Cities", "Celadon City"},	--CELADON_DEPT_STORE_4F
		[9] =	{"Kanto Cities", "Celadon City"},	--CELADON_DEPT_STORE_5F
		[10] =	{"Kanto Cities", "Celadon City"},	--CELADON_DEPT_STORE_6F
		[11] =	{"Kanto Cities", "Celadon City"},	--CELADON_DEPT_STORE_ELEVATOR
		[12] =	{"Kanto Cities", "Celadon City"},	--CELADON_MANSION_1F
		[13] =	{"Kanto Cities", "Celadon City"},	--CELADON_MANSION_2F
		[14] =	{"Kanto Cities", "Celadon City"},	--CELADON_MANSION_3F
		[15] =	{"Kanto Cities", "Celadon City"},	--CELADON_MANSION_ROOF
		[16] =	{"Kanto Cities", "Celadon City"},	--CELADON_MANSION_ROOF_HOUSE
		[17] =	{"Kanto Cities", "Celadon City"},	--CELADON_POKECENTER_1F
		[18] =	{"Kanto Cities", "Celadon City"},	--CELADON_POKECENTER_2F_BETA
		[19] =	{"Kanto Cities", "Celadon City"},	--CELADON_GAME_CORNER
		[20] =	{"Kanto Cities", "Celadon City"},	--CELADON_GAME_CORNER_PRIZE_ROOM
		[21] =	{"Kanto Cities", "Celadon City"},	--CELADON_GYM
		[22] =	{"Kanto Cities", "Celadon City"},	--CELADON_CAFE
		[23] =	{"Kanto Routes", "Route 16"},		--ROUTE_16_FUCHSIA_SPEECH_HOUSE
		[24] =	{"Kanto Routes", "Route 16"},		--ROUTE_16_GATE
		[25] =	{"Kanto Routes", "Route 7"},		--ROUTE_7_SAFFRON_GATE
		[26] =	{"Kanto Routes", "Route 17"},		--ROUTE_17_ROUTE_18_GATE
	},
	[22] =	{
		[1] =	{"Johto Routes", "Route 40"},		--ROUTE_40
		[2] =	{"Johto Routes", "Route 41"},		--ROUTE_41
		[3] =	{"Johto Cities", "Cianwood City"},	--CIANWOOD_CITY
		[4] =	{"Johto Cities", "Cianwood City"},	--MANIAS_HOUSE
		[5] =	{"Johto Cities", "Cianwood City"},	--CIANWOOD_GYM
		[6] =	{"Johto Cities", "Cianwood City"},	--CIANWOOD_POKECENTER_1F
		[7] =	{"Johto Cities", "Cianwood City"},	--CIANWOOD_PHARMACY
		[8] =	{"Johto Cities", "Cianwood City"},	--CIANWOOD_PHOTO_STUDIO
		[9] =	{"Johto Cities", "Cianwood City"},	--CIANWOOD_LUGIA_SPEECH_HOUSE
		[10] =	{"Johto Cities", "Cianwood City"},	--POKE_SEERS_HOUSE
		[11] =	{},									--BATTLE_TOWER_1F
		[12] =	{},									--BATTLE_TOWER_BATTLE_ROOM
		[13] =	{},									--BATTLE_TOWER_ELEVATOR
		[14] =	{},									--BATTLE_TOWER_HALLWAY
		[15] =	{},									--ROUTE_40_BATTLE_TOWER_GATE
		[16] =	{},									--BATTLE_TOWER_OUTSIDE
	},
	[23] =	{
		[1] =	{"Kanto Routes", "Route 2"},		--ROUTE_2
		[2] =	{"Kanto Routes", "Route 22"},		--ROUTE_22
		[3] =	{"Kanto Cities", "Viridian City"},	--VIRIDIAN_CITY
		[4] =	{"Kanto Cities", "Viridian City"},	--VIRIDIAN_GYM
		[5] =	{"Kanto Cities", "Viridian City"},	--VIRIDIAN_NICKNAME_SPEECH_HOUSE
		[6] =	{"Kanto Cities", "Viridian City"},	--TRAINER_HOUSE_1F
		[7] =	{"Kanto Cities", "Viridian City"},	--TRAINER_HOUSE_B1F
		[8] =	{"Kanto Cities", "Viridian City"},	--VIRIDIAN_MART
		[9] =	{"Kanto Cities", "Viridian City"},	--VIRIDIAN_POKECENTER_1F
		[10] =	{"Kanto Cities", "Viridian City"},	--VIRIDIAN_POKECENTER_2F_BETA
		[11] =	{"Kanto Routes", "Route 2"},		--ROUTE_2_NUGGET_HOUSE
		[12] =	{"Kanto Routes", "Route 2"},		--ROUTE_2_GATE
		[13] =	{"Kanto Dungeons", "Victory Road"},	--VICTORY_ROAD_GATE
	},
	[24] =	{
		[1] =	{"Kanto Routes", "Route 26"},		--ROUTE_26
		[2] =	{"Kanto Routes", "Route 27"},		--ROUTE_27
		[3] =	{"Johto Routes", "Route 29"},		--ROUTE_29
		[4] =	{"Johto Cities", "New Bark Town"},	--NEW_BARK_TOWN
		[5] =	{"Johto Cities", "New Bark Town"},	--ELMS_LAB
		[6] =	{"Johto Cities", "New Bark Town"},	--PLAYERS_HOUSE_1F
		[7] =	{"Johto Cities", "New Bark Town"},	--PLAYERS_HOUSE_2F
		[8] =	{"Johto Cities", "New Bark Town"},	--PLAYERS_NEIGHBORS_HOUSE
		[9] =	{"Johto Cities", "New Bark Town"},	--ELMS_HOUSE
		[10] =	{"Kanto Routes", "Route 26"},		--ROUTE_26_HEAL_HOUSE
		[11] =	{"Kanto Routes", "Route 26"},		--DAY_OF_WEEK_SIBLINGS_HOUSE
		[12] =	{"Kanto Routes", "Route 27"},		--ROUTE_27_SANDSTORM_HOUSE
		[13] =	{"Johto Routes", "Route 29"},		--ROUTE_29_ROUTE_46_GATE
	},
	[25] =	{
		[1] =	{"Kanto Routes", "Route 5"},		--ROUTE_5
		[2] =	{"Kanto Cities", "Saffron City"},	--SAFFRON_CITY
		[3] =	{"Kanto Cities", "Saffron City"},	--FIGHTING_DOJO
		[4] =	{"Kanto Cities", "Saffron City"},	--SAFFRON_GYM
		[5] =	{"Kanto Cities", "Saffron City"},	--SAFFRON_MART
		[6] =	{"Kanto Cities", "Saffron City"},	--SAFFRON_POKECENTER_1F
		[7] =	{"Kanto Cities", "Saffron City"},	--SAFFRON_POKECENTER_2F_BETA
		[8] =	{"Kanto Cities", "Saffron City"},	--MR_PSYCHICS_HOUSE
		[9] =	{"Kanto Cities", "Saffron City"},	--SAFFRON_MAGNET_TRAIN_STATION
		[10] =	{"Kanto Cities", "Saffron City"},	--SILPH_CO_1F
		[11] =	{"Kanto Cities", "Saffron City"},	--COPYCATS_HOUSE_1F
		[12] =	{"Kanto Cities", "Saffron City"},	--COPYCATS_HOUSE_2F
		[13] =	{"Kanto Routes", "Route 5"},		--ROUTE_5_UNDERGROUND_PATH_ENTRANCE
		[14] =	{"Kanto Routes", "Route 5"},		--ROUTE_5_SAFFRON_GATE
		[15] =	{"Kanto Routes", "Route 5"},		--ROUTE_5_CLEANSE_TAG_HOUSE
	},
	[26] =	{
		[1] =	{"Johto Routes", "Route 30"},			--ROUTE_30
		[2] =	{"Johto Routes", "Route 31"},			--ROUTE_31
		[3] =	{"Johto Cities", "Cherrygrove City"},	--CHERRYGROVE_CITY
		[4] =	{"Johto Cities", "Cherrygrove City"},	--CHERRYGROVE_MART
		[5] =	{"Johto Cities", "Cherrygrove City"},	--CHERRYGROVE_POKECENTER_1F
		[6] =	{"Johto Cities", "Cherrygrove City"},	--CHERRYGROVE_GYM_SPEECH_HOUSE
		[7] =	{"Johto Cities", "Cherrygrove City"},	--GUIDE_GENTS_HOUSE
		[8] =	{"Johto Cities", "Cherrygrove City"},	--CHERRYGROVE_EVOLUTION_SPEECH_HOUSE
		[9] =	{"Johto Routes", "Route 30"},			--ROUTE_30_BERRY_HOUSE
		[10] =	{"Johto Routes", "Route 30"},			--MR_POKEMONS_HOUSE
		[11] =	{"Johto Routes", "Route 31"},			--ROUTE_31_VIOLET_GATE
	}
}